/**
 * Bootstrap codegen — transforms TS bootstrap files into Zen-C string constants.
 * These strings get compiled into the native binary and injected into WebView/workers.
 *
 * Generates three functions:
 *   - zapp_webview_bootstrap_script() — WebView bridge (invoke, events, workers, sync, drag)
 *   - zapp_worker_bootstrap_script()  — Unified worker bridge (used by both webview-spawned
 *     workers and headless workers)
 *   - zapp_bare_worker_bootstrap_script() — Bare-engine specific dispatcher setup
 *     (`__zappBridge.invokeService`, `_dispatchMessage`, `dispatchEventToAll`,
 *     `syncWait`/`syncNotify`, `createWindow`, JSON.stringify wrappers around the
 *     C *Raw trampolines). Runs on every bare-* engine to install the
 *     shared JS-side bridge methods on globalThis.__zappBridge.
 *
 * Usage: called by CLI during build, or standalone:
 *   bun bootstrap/codegen.ts [outputDir]
 */

import path from "node:path";
import { mkdir } from "node:fs/promises";

const bootstrapDir = import.meta.dir;

/** Bundle + minify a TS file and escape for C string literal. */
async function bundleAndEscape(entrypoint: string): Promise<string> {
  const result = await Bun.build({
    entrypoints: [entrypoint],
    minify: true,
    target: "browser",
  });

  if (!result.success) {
    const errors = result.logs.map((l) => l.message).join("\n");
    throw new Error(`[zapp] bootstrap build failed for ${entrypoint}:\n${errors}`);
  }

  const code = await result.outputs[0].text();

  return code
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "");
}

/** Bundle + minify a TS file, returning the RAW JS (no C-string escaping). */
async function bundleRaw(entrypoint: string): Promise<string> {
  const result = await Bun.build({
    entrypoints: [entrypoint],
    minify: true,
    target: "browser",
  });
  if (!result.success) {
    const errors = result.logs.map((l) => l.message).join("\n");
    throw new Error(`[zapp] bootstrap build failed for ${entrypoint}:\n${errors}`);
  }
  return await result.outputs[0].text();
}

/**
 * Bundle + minify the WebView bootstrap and return the RAW JS string.
 * Used by the Nim build path, whose `renderBootstrapNim` does its own
 * (raw-string-literal) escaping — unlike `generateBootstrap` which
 * escapes for embedding in a Zen-C C-string. Same source + bundler as
 * the `.zc` path so the two stay in lockstep.
 */
export async function bundleWebviewBootstrapRaw(): Promise<string> {
  return bundleRaw(path.join(bootstrapDir, "webview.ts"));
}

/**
 * Generate .zapp/zapp_bootstrap.zc containing minified bridge JS
 * as Zen-C functions returning C strings.
 */
export async function generateBootstrap(outputDir: string): Promise<string> {
  await mkdir(outputDir, { recursive: true });

  // Bundle all bootstraps in parallel
  const [webviewEscaped, workerEscaped, bareWorkerEscaped] = await Promise.all([
    bundleAndEscape(path.join(bootstrapDir, "webview.ts")),
    bundleAndEscape(path.join(bootstrapDir, "worker.ts")),
    bundleAndEscape(path.join(bootstrapDir, "bare-worker.ts")),
  ]);

  const zcContent = `// AUTO-GENERATED by zapp CLI. Do not edit.
// Source: bootstrap/webview.ts, bootstrap/worker.ts, bootstrap/bare-worker.ts

fn zapp_webview_bootstrap_script() -> string {
    raw { return "${webviewEscaped}"; }
    return "";
}

fn zapp_worker_bootstrap_script() -> string {
    raw { return "${workerEscaped}"; }
    return "";
}

fn zapp_bare_worker_bootstrap_script() -> string {
    raw { return "${bareWorkerEscaped}"; }
    return "";
}
`;

  const outPath = path.join(outputDir, "zapp_bootstrap.zc");
  await Bun.write(outPath, zcContent);
  return outPath;
}

// Standalone invocation: bun bootstrap/codegen.ts [outputDir]
if (import.meta.main) {
  const outputDir = process.argv[2] || path.join(process.cwd(), ".zapp");
  const outPath = await generateBootstrap(outputDir);
  console.log(`[zapp] bootstrap generated: ${outPath}`);
}
