import console from "std/console";
import { Channel } from "std/channel";
import json from "std/json";
import { Once, OnceLifetime } from "std/sync";
import { thread } from "std/thread";
import { delay } from "std/time";
import native from "zapp_worker_zjs.h";
import {
  Service,
  Services,
  ServicesBuilder,
  createServices,
} from "../../framework/services.zs";
import {
  WorkerCommand,
  WorkerMessage,
} from "./worker-command.zs";
import {
  createWorkerProbeService,
} from "./probe-service.zs";
import {
  WorkerEngine,
  WorkerInbox,
  WorkerLifecycle,
  WorkerModule,
  createWorkerInbox,
  createWorkerMailbox,
  runWorkerEngine,
} from "../../framework/worker/engine.zs";

const workerModule: cstring = "export function onCommand(left, right) { setTimeout(() => { __zappServiceAdd(left, right); }, 5); }";

readonly class WorkerServicesStore {
  readonly services: Services;
  readonly lifecycleMarker: i32 on thread.main;
}

const workerServices = Once<WorkerServicesStore>();

export struct WorkerServicesBuilder {
  routes: ServicesBuilder;

  // Build marker adapted to registerGenerated by the same checked overlay
  // mechanism used for ApplicationServicesBuilder.register.
  function register<T>(
    inout this,
    name: String,
    service: T
  ): void {}

  function registerGenerated<T: Service>(
    inout this,
    name: String,
    service: T
  ): void {
    this.routes.register(move name, service);
  }

  function freeze(move this): Services {
    const { routes } = move this;
    return routes.freeze();
  }
}

function initializeWorkerServices(
): OnceLifetime<WorkerServicesStore> on thread.main {
  let services = WorkerServicesBuilder({ routes: createServices() });
  services.register("probe", createWorkerProbeService());
  const configured = services.freeze();
  const store = new WorkerServicesStore({
    services: move configured,
    lifecycleMarker: 1,
  });
  return workerServices.initialize(move store);
}

// The embedded engine enters the same generated service adapter and frozen
// synchronous router used by a Zapp application. This scalar C ABI is only the
// first host-binding proof; it is not the eventual generic worker bridge.
function decodeWorkerServiceResult(in payload: String): i32 {
  const parsed = attempt json.parse(in payload);
  match (parsed) {
    failure(_) => return -101;
    success(value) => match (in value) {
      number(number) => {
        const converted = attempt number.toI64();
        return match (converted) {
          success(integer) => i32(integer);
          failure(_) => -103;
        };
      }
      _ => return -102;
    }
  }
}

export c function zapp_worker_probe_add(left: i32, right: i32): i32 {
  const store = workerServices.get();
  const services = store.services;
  return invokeWorkerProbe(in services, left, right);
}

function invokeWorkerProbe(
  in services: Services,
  left: i32,
  right: i32
): i32 {
  const outcome = services.invoke(
    "probe.add",
    `{"left":${left},"right":${right}}`
  );
  return match (outcome) {
    success(payload) => decodeWorkerServiceResult(in payload);
    failure(_) => -104;
    typedFailure(_) => -105;
  };
}

struct ZjsWorkerEngine implements WorkerEngine<WorkerCommand> {
  handle: native.ZappZjsEngine;

  function load(
    inout this,
    in module: WorkerModule
  ): i32 {
    return native.zapp_zjs_engine_evaluate_module(
      this.handle,
      module.source
    );
  }

  function hasPendingWork(): boolean {
    return native.zapp_zjs_engine_has_pending_work(this.handle) != 0;
  }

  function dispatch(inout this, in command: WorkerCommand): i32 {
    return match (in command) {
      message(value) => native.zapp_zjs_engine_dispatch(
        this.handle,
        value.left,
        value.right
      );
    };
  }

  function nextWakeMilliseconds(): i64 {
    return native.zapp_zjs_engine_next_wake_milliseconds(this.handle);
  }

  function pump(inout this): i32 {
    return native.zapp_zjs_engine_pump(this.handle);
  }

  function isComplete(): boolean {
    return native.zapp_zjs_engine_is_complete(this.handle) != 0;
  }

  function result(): i32 {
    return native.zapp_zjs_engine_result(this.handle);
  }
}

function executeWorkerModule(
  in inbox: WorkerInbox<WorkerCommand>
): WorkerLifecycle {
  const engine = native.zapp_zjs_engine_create();
  if (engine == null) return WorkerLifecycle.failed(100);

  let adapter = ZjsWorkerEngine({ handle: move engine });
  const module = WorkerModule({ source: workerModule });
  return runWorkerEngine(inout adapter, in module, in inbox);
}

async function runWorkerProof(): i32 {
  const { sender, receiver } = Channel<WorkerCommand>.bounded(1);
  const mailbox = createWorkerMailbox<WorkerCommand>(move sender);
  const inbox = createWorkerInbox<WorkerCommand>(move receiver, mailbox);
  const worker = thread.spawn(
    move (): WorkerLifecycle => executeWorkerModule(in inbox)
  );
  await delay(1);
  console.log("ZJS worker channel ready");
  const posted = attempt await mailbox.post(WorkerCommand.message(WorkerMessage({
    left: 20,
    right: 22,
  })));
  match (posted) {
    success => {}
    failure(_) => return 1;
  }
  console.log("ZJS worker command accepted");

  const result = await worker;
  const value = match (result) {
    stopped(observed) => observed;
    cancelled(_) => -2;
    failed(code) => -code;
  };
  if (value != 42) return 2;

  const {
    sender: cancellationSender,
    receiver: cancellationReceiver,
  } = Channel<WorkerCommand>.bounded(1);
  const cancellation = createWorkerMailbox<WorkerCommand>(
    move cancellationSender
  );
  const cancellationInbox = createWorkerInbox<WorkerCommand>(
    move cancellationReceiver,
    cancellation
  );
  const cancelledWorker = thread.spawn(
    move (): WorkerLifecycle => executeWorkerModule(in cancellationInbox)
  );
  await delay(1);
  if (!cancellation.requestCancellation()) return 3;
  const cancelledResult = await cancelledWorker;
  const cancelledCleanly = match (cancelledResult) {
    cancelled(_) => true;
    _ => false;
  };
  if (!cancelledCleanly) return 4;

  console.log(`ZJS worker processed a Z command and returned ${value}`);
  console.log("ZJS worker observed cancellation and joined cleanly");
  return 0;
}

async function main(): i32 on thread.main {
  const serviceLifetime = initializeWorkerServices();
  return await runWorkerProof();
}
