import console from "std/console";
import { Channel } from "std/channel";
import json from "std/json";
import { Once, OnceLifetime } from "std/sync";
import { thread } from "std/thread";
import { delay } from "std/time";
import embed from "std/embed";
import native from "zapp_worker_zjs.h";
import {
  Service,
  Services,
  ServicesBuilder,
  createServices,
} from "../../framework/services.zs";
import {
  WorkerCommand,
  WorkerMessage,
  WorkerResponse,
} from "../../framework/worker/message.zs";
import {
  createWorkerProbeService,
} from "./probe-service.zs";
import {
  WorkerEngine,
  WorkerInbox,
  createWorkerInbox,
  createWorkerMailbox,
  runWorkerEngine,
} from "../../framework/worker/engine.zs";
import {
  WorkerLifecycle,
  WorkerModule,
} from "../../framework/worker/types.zs";

const workerModuleSource: embed.StaticBytes = embed.bytes("./worker-proof.mjs");

readonly class WorkerServicesStore {
  readonly services: Services;
  readonly lifecycleMarker: i32 on thread.main;
}

const workerServices = Once<WorkerServicesStore>();

export struct WorkerServicesBuilder {
  routes: ServicesBuilder;

  // Build marker adapted to registerGenerated by the same checked overlay
  // mechanism used for ApplicationServices.register.
  function register<T>(
    inout this,
    name: String,
    service: T
  ): void {}

  function registerGenerated<T: Service>(
    inout this,
    name: String,
    service: T
  ): void {
    this.routes.register(move name, service);
  }

  function freeze(move this): Services {
    const { routes } = move this;
    return routes.freeze();
  }
}

function initializeWorkerServices(
): OnceLifetime<WorkerServicesStore> on thread.main {
  let services = WorkerServicesBuilder({ routes: createServices() });
  services.register("probe", createWorkerProbeService());
  const configured = services.freeze();
  const store = new WorkerServicesStore({
    services: move configured,
    lifecycleMarker: 1,
  });
  return workerServices.initialize(move store);
}

// The embedded engine enters the same generated service adapter and frozen
// synchronous router used by a Zapp application. This scalar C ABI is only the
// first host-binding proof; it is not the eventual generic worker bridge.
function decodeWorkerServiceResult(in payload: String): i32 {
  const parsed = attempt json.parse(in payload);
  match (parsed) {
    failure(_) => return -101;
    success(value) => match (in value) {
      number(number) => {
        const converted = attempt number.toI64();
        return match (converted) {
          success(integer) => i32(integer);
          failure(_) => -103;
        };
      }
      _ => return -102;
    }
  }
}

export c function zapp_worker_probe_add(left: i32, right: i32): i32 {
  const store = workerServices.get();
  const services = store.services;
  return invokeWorkerProbe(in services, left, right);
}

function invokeWorkerProbe(
  in services: Services,
  left: i32,
  right: i32
): i32 {
  const outcome = services.invoke(
    "probe.add",
    `{"left":${left},"right":${right}}`
  );
  return match (outcome) {
    success(payload) => decodeWorkerServiceResult(in payload);
    failure(_) => -104;
    typedFailure(_) => -105;
  };
}

struct ZjsWorkerEngine implements WorkerEngine<WorkerCommand> {
  handle: native.ZappZjsEngine;

  function load(
    inout this,
    in module: WorkerModule
  ): i32 {
    return native.zapp_zjs_engine_evaluate_module(
      this.handle,
      module.source,
      module.name
    );
  }

  function hasPendingWork(): boolean {
    return native.zapp_zjs_engine_has_pending_work(this.handle) != 0;
  }

  function dispatch(inout this, in command: WorkerCommand): i32 {
    return match (in command) {
      message(value) => native.zapp_zjs_engine_dispatch(
        this.handle,
        value.channel,
        value.payload
      );
    };
  }

  function nextWakeMilliseconds(): i64 {
    return native.zapp_zjs_engine_next_wake_milliseconds(this.handle);
  }

  function pump(inout this): i32 {
    return native.zapp_zjs_engine_pump(this.handle);
  }

  function isComplete(): boolean {
    return native.zapp_zjs_engine_is_complete(this.handle) != 0;
  }

  function result(): i32 {
    return native.zapp_zjs_engine_result(this.handle);
  }
}

enum ZjsWorkerRun {
  completed WorkerResponse,
  cancelled i32,
  failed i32,
}

function executeWorkerModule(
  in inbox: WorkerInbox<WorkerCommand>
): ZjsWorkerRun {
  const engine = native.zapp_zjs_engine_create();
  if (engine == null) return ZjsWorkerRun.failed(100);

  let adapter = ZjsWorkerEngine({ handle: move engine });
  const module = WorkerModule({
    source: workerModuleSource,
    name: "/zapp/internal/worker-proof.mjs",
  });
  const lifecycle = runWorkerEngine(inout adapter, in module, in inbox);
  return match (lifecycle) {
    cancelled(code) => {
      const channel = native.zapp_zjs_engine_response_channel(adapter.handle);
      const payload = native.zapp_zjs_engine_response_payload(adapter.handle);
      if (channel == null || payload == null) {
        return ZjsWorkerRun.cancelled(code);
      }
      return ZjsWorkerRun.completed(WorkerResponse({
        channel: String.from(channel),
        payload: String.from(payload),
      }));
    }
    failed(code) => ZjsWorkerRun.failed(code);
    stopped(_) => {
      const channel = native.zapp_zjs_engine_response_channel(adapter.handle);
      const payload = native.zapp_zjs_engine_response_payload(adapter.handle);
      if (channel == null || payload == null) return ZjsWorkerRun.failed(101);
      return ZjsWorkerRun.completed(WorkerResponse({
        channel: String.from(channel),
        payload: String.from(payload),
      }));
    }
  };
}

async function runWorkerProof(): i32 {
  const { sender, receiver } = Channel<WorkerCommand>.bounded(1);
  const mailbox = createWorkerMailbox<WorkerCommand>(move sender);
  const inbox = createWorkerInbox<WorkerCommand>(move receiver, mailbox);
  const worker = thread.spawn(
    move (): ZjsWorkerRun => executeWorkerModule(in inbox)
  );
  await delay(1);
  console.log("ZJS worker channel ready");
  const posted = attempt await mailbox.sender.send(WorkerCommand.message(WorkerMessage({
    channel: "add",
    payload: "{\"left\":20,\"right\":22}",
  })));
  match (posted) {
    success => {}
    failure(_) => return 1;
  }
  console.log("ZJS worker accepted channel add");

  await delay(10);
  if (!mailbox.requestCancellation()) return 2;
  const result = await worker;
  let value = 0;
  match (result) {
    completed(response) => {
      if (response.channel != "added") return 2;
      value = decodeWorkerServiceResult(in response.payload);
    }
    cancelled(_) => return 2;
    failed(_) => return 2;
  }
  if (value != 42) return 2;

  const {
    sender: cancellationSender,
    receiver: cancellationReceiver,
  } = Channel<WorkerCommand>.bounded(1);
  const cancellation = createWorkerMailbox<WorkerCommand>(
    move cancellationSender
  );
  const cancellationInbox = createWorkerInbox<WorkerCommand>(
    move cancellationReceiver,
    cancellation
  );
  const cancelledWorker = thread.spawn(
    move (): ZjsWorkerRun => executeWorkerModule(in cancellationInbox)
  );
  await delay(1);
  if (!cancellation.requestCancellation()) return 3;
  const cancelledResult = await cancelledWorker;
  const cancelledCleanly = match (cancelledResult) {
    cancelled(_) => true;
    _ => false;
  };
  if (!cancelledCleanly) return 4;

  console.log(`ZJS worker replied on channel added with ${value}`);
  console.log("ZJS worker observed cancellation and joined cleanly");
  return 0;
}

async function main(): i32 on thread.main {
  const serviceLifetime = initializeWorkerServices();
  return await runWorkerProof();
}
