import "app/app.zc";

fn ping_service(_app: App*, args: string) -> string {
    return args;
}

fn on_window_ready(id: int, handle: void*) -> void {
    let win = Window{id: id, handle: handle};
    println "[native] window ready callback fired!";
    win.show();
}

fn on_window_focus(_data: WindowEventData*) -> int {
    println "[native] window focused!";
    return 0;
}

fn on_window_blur(_data: WindowEventData*) -> int {
    println "[native] window blurred!";
    return 0;
}

fn on_window_resize(data: WindowEventData*) -> int {
    let w: int = data.width;
    let h: int = data.height;
    let x: int = data.x;
    let y: int = data.y;
    println "[native] window resized to {w}x{h} at ({x},{y})";
    return 0;
}

fn on_window_move(data: WindowEventData*) -> int {
    let x: int = data.x;
    let y: int = data.y;
    println "[native] window moved to ({x},{y})";
    return 0;
}

fn on_window_close(_data: WindowEventData*) -> int {
    println "[native] window close requested!";
    return 0; // ALLOW (return 1 for CANCEL)
}

fn run_app() -> int {
    let config = AppConfig{
        name: "Zapp Playground",
        applicationShouldTerminateAfterLastWindowClosed: true,
        webContentInspectable: 1, // -1 = inherit from build (dev=true, prod=false), 0 = off, 1 = on
        maxWorkers: 50,
        qjsStackSize: 0,
    };
    let app = App::new(config);

    app.service.add("ping", ping_service);

    // Main window
    let opts = window_options_default("Zapp Playground");
    opts.width = 900;
    opts.height = 650;
    opts.visible = false;
    let win = app.window.create(&opts);
    win.on_ready(on_window_ready);
    win.on(WindowEvent.RESIZE, on_window_resize);
    win.on(WindowEvent.CLOSE, on_window_close);

    return app.run();
}
