// macOS WebView (WKWebView) implementation — pure Objective-C.
// Custom scheme handler, message handler, bootstrap injection.

#import <Cocoa/Cocoa.h>
#import <WebKit/WebKit.h>
#import "webview.h"

// --- Forward declarations from Zen-C / other .m files ---
extern void* app_get_active(void);

// Build-time config functions (generated by CLI into zapp_build_config.zc)
extern const char* zapp_build_initial_url(void);
extern int zapp_build_use_embedded_assets(void);
extern const char* zapp_build_csp(void);
extern const char* app_get_allowed_navigation_json(void);
extern int zapp_build_is_dev(void);

// Bootstrap script (generated from TS)
extern const char* zapp_webview_bootstrap_script(void);

// App config accessors
extern const char* app_get_bootstrap_name(void);
extern bool app_get_bootstrap_web_content_inspectable(void);
extern bool app_get_bootstrap_application_should_terminate_after_last_window_closed(void);
extern int app_get_bootstrap_max_workers(void);

// Service bindings
extern const char* service_get_manifest_json(void);

// --- Helpers ---

// Single-pass JS string escape — one allocation instead of four.
static NSString* zapp_escape_js_string(const char* raw) {
    if (!raw || raw[0] == '\0') return @"";
    size_t len = strlen(raw);
    // Worst case: every char needs escaping (2x)
    char* buf = (char*)malloc(len * 2 + 1);
    if (!buf) return @"";
    size_t j = 0;
    for (size_t i = 0; i < len; i++) {
        switch (raw[i]) {
            case '\\': buf[j++] = '\\'; buf[j++] = '\\'; break;
            case '\'': buf[j++] = '\\'; buf[j++] = '\''; break;
            case '\n': buf[j++] = '\\'; buf[j++] = 'n'; break;
            case '\r': buf[j++] = '\\'; buf[j++] = 'r'; break;
            default:   buf[j++] = raw[i]; break;
        }
    }
    buf[j] = '\0';
    NSString* result = [NSString stringWithUTF8String:buf];
    free(buf);
    return result;
}

const char* darwin_escape_js_string(const char* raw) {
    return [zapp_escape_js_string(raw) UTF8String];
}

static NSDictionary* zapp_mime_map = nil;

static NSString* zapp_mime_for_path(NSString* path) {
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        zapp_mime_map = @{
            @"html": @"text/html", @"htm": @"text/html",
            @"css": @"text/css", @"js": @"application/javascript",
            @"mjs": @"application/javascript", @"json": @"application/json",
            @"png": @"image/png", @"jpg": @"image/jpeg", @"jpeg": @"image/jpeg",
            @"gif": @"image/gif", @"svg": @"image/svg+xml",
            @"ico": @"image/x-icon", @"woff": @"font/woff",
            @"woff2": @"font/woff2", @"ttf": @"font/ttf",
            @"wasm": @"application/wasm",
        };
    });
    NSString* ext = [[path pathExtension] lowercaseString];
    return zapp_mime_map[ext] ?: @"application/octet-stream";
}

static NSURL* zapp_initial_url(void) {
    const char* configuredUrl = zapp_build_initial_url();
    if (configuredUrl && configuredUrl[0] != '\0') {
        return [NSURL URLWithString:[NSString stringWithUTF8String:configuredUrl]];
    }
    return [NSURL URLWithString:@"zapp://index.html"];
}

extern const char* zapp_build_asset_root(void);

static NSString* zapp_asset_root_path(void) {
    // 1. Check build config (set by CLI for prod builds)
    const char* configured = zapp_build_asset_root();
    if (configured && configured[0] != '\0') {
        return [NSString stringWithUTF8String:configured];
    }
    // 2. Check NSBundle resourcePath (for .app bundles)
    NSString* bundleResources = [[NSBundle mainBundle] resourcePath];
    NSString* indexInBundle = [bundleResources stringByAppendingPathComponent:@"index.html"];
    if ([[NSFileManager defaultManager] fileExistsAtPath:indexInBundle]) {
        return bundleResources;
    }
    // 3. Fallback: current working directory (dev mode without .app)
    char cwd[1024];
    if (getcwd(cwd, sizeof(cwd))) {
        return [NSString stringWithUTF8String:cwd];
    }
    return @".";
}

// --- Asset Scheme Handler (zapp://) ---

@interface ZappAssetSchemeHandler : NSObject <WKURLSchemeHandler>
@end

@implementation ZappAssetSchemeHandler
- (void)webView:(WKWebView*)webView startURLSchemeTask:(id<WKURLSchemeTask>)task {
    (void)webView;
    NSURL* url = [task request].URL;
    NSString* host = url.host ?: @"";
    NSString* path = url.path ?: @"/";

    NSString* rel = path;
    if ((rel.length == 0 || [rel isEqualToString:@"/"]) && host.length > 0) {
        rel = [@"/" stringByAppendingString:host];
    } else if (host.length > 0 && ![host isEqualToString:@"app"]) {
        if ([path hasPrefix:@"/assets/"]) rel = path;
    }
    if ([rel isEqualToString:@"/"] || rel.length == 0) rel = @"/index.html";
    while ([rel hasPrefix:@"/"]) rel = [rel substringFromIndex:1];

    // Block path traversal
    if ([rel rangeOfString:@".."].location != NSNotFound) {
        NSHTTPURLResponse* forbidden = [[NSHTTPURLResponse alloc]
            initWithURL:url statusCode:403 HTTPVersion:@"HTTP/1.1"
            headerFields:@{ @"Content-Type": @"text/plain" }];
        [task didReceiveResponse:forbidden];
        [task didReceiveData:[@"Forbidden" dataUsingEncoding:NSUTF8StringEncoding]];
        [task didFinish];
        return;
    }

    // Embedded asset lookup (brotli decompression)
    if (zapp_build_use_embedded_assets()) {
        #ifdef ZAPP_EMBEDDED_ASSET_DEFINED
        extern ZappEmbeddedAsset zapp_embedded_assets[];
        extern int zapp_embedded_assets_count;
        NSString* lookupPath = [@"/" stringByAppendingString:rel];
        for (int i = 0; i < zapp_embedded_assets_count; i++) {
            NSString* assetPath = [NSString stringWithUTF8String:zapp_embedded_assets[i].path];
            if ([assetPath isEqualToString:lookupPath]) {
                NSData* assetData;
                if (zapp_embedded_assets[i].is_brotli && zapp_embedded_assets[i].uncompressed_len > 0) {
                    uint8_t* out = malloc(zapp_embedded_assets[i].uncompressed_len);
                    size_t decoded = compression_decode_buffer(
                        out, zapp_embedded_assets[i].uncompressed_len,
                        zapp_embedded_assets[i].data, zapp_embedded_assets[i].len,
                        NULL, COMPRESSION_BROTLI);
                    assetData = [NSData dataWithBytesNoCopy:out length:decoded freeWhenDone:YES];
                } else {
                    assetData = [NSData dataWithBytes:zapp_embedded_assets[i].data
                                              length:zapp_embedded_assets[i].len];
                }
                NSString* mime = zapp_mime_for_path(rel);
                NSHTTPURLResponse* resp = [[NSHTTPURLResponse alloc]
                    initWithURL:url statusCode:200 HTTPVersion:@"HTTP/1.1"
                    headerFields:@{ @"Content-Type": mime }];
                [task didReceiveResponse:resp];
                [task didReceiveData:assetData];
                [task didFinish];
                return;
            }
        }
        #endif
    }

    // Filesystem fallback (dev mode or asset not found in embedded)
    NSString* assetRoot = zapp_asset_root_path();
    NSString* filePath = [assetRoot stringByAppendingPathComponent:rel];
    NSData* data = [NSData dataWithContentsOfFile:filePath];

    if (!data) {
        NSHTTPURLResponse* notFound = [[NSHTTPURLResponse alloc]
            initWithURL:url statusCode:404 HTTPVersion:@"HTTP/1.1"
            headerFields:@{ @"Content-Type": @"text/plain" }];
        [task didReceiveResponse:notFound];
        [task didReceiveData:[@"Not Found" dataUsingEncoding:NSUTF8StringEncoding]];
        [task didFinish];
        return;
    }

    NSString* mime = zapp_mime_for_path(rel);
    NSHTTPURLResponse* response = [[NSHTTPURLResponse alloc]
        initWithURL:url statusCode:200 HTTPVersion:@"HTTP/1.1"
        headerFields:@{ @"Content-Type": mime, @"Content-Length": [@(data.length) stringValue] }];
    [task didReceiveResponse:response];
    [task didReceiveData:data];
    [task didFinish];
}

- (void)webView:(WKWebView*)webView stopURLSchemeTask:(id<WKURLSchemeTask>)task {
    (void)webView;
    (void)task;
}
@end

// --- Message Handler (JS → Native bridge) ---

@interface ZappMsgHandler : NSObject <WKScriptMessageHandler>
@end

extern int32_t darwin_window_id_for_webview(void* webview);
extern void zapp_handle_message_from_window(void* app, char* msg, int32_t window_id);

@implementation ZappMsgHandler
- (void)userContentController:(WKUserContentController*)ucc didReceiveScriptMessage:(WKScriptMessage*)msg {
    (void)ucc;
    id body = [msg body];
    if (![body isKindOfClass:[NSString class]]) return;
    const char* raw_msg = [(NSString*)body UTF8String];
    if (!raw_msg) return;
    int32_t window_id = darwin_window_id_for_webview((__bridge void*)msg.webView);

    // Fast path: drag region messages are the most frequent (60Hz on mousemove).
    // Detect with simple string prefix check — avoids JSON parse entirely.
    if (raw_msg[0] == '{' && raw_msg[1] == '"' && raw_msg[2] == 't' &&
        raw_msg[3] == '"' && raw_msg[4] == ':' && raw_msg[5] == '4' &&
        strstr(raw_msg, "\"setDragRegion\"") != NULL) {
        BOOL drag = strstr(raw_msg, "\"drag\":true") != NULL;
        extern void darwin_webview_set_drag_region(int32_t window_id, bool drag);
        darwin_webview_set_drag_region(window_id, drag);
        return;
    }

    void* app_ptr = app_get_active();
    if (app_ptr != NULL) {
        zapp_handle_message_from_window(app_ptr, (char*)raw_msg, window_id);
    }
}
@end

// --- WebView Subclass (drag regions, context menu filtering) ---

@interface ZappWebView : WKWebView
@property (nonatomic, assign) BOOL inDragRegion;
@property (nonatomic, assign) BOOL acceptFirstMouse;
@end

@implementation ZappWebView
- (instancetype)initWithFrame:(NSRect)frame configuration:(WKWebViewConfiguration*)config {
    self = [super initWithFrame:frame configuration:config];
    if (self) {
        _inDragRegion = NO;
        _acceptFirstMouse = YES;
    }
    return self;
}
- (void)mouseDown:(NSEvent*)event {
    if (self.inDragRegion) {
        [self.window performWindowDragWithEvent:event];
        return;
    }
    [super mouseDown:event];
}
- (BOOL)mouseDownCanMoveWindow { return self.inDragRegion; }
- (BOOL)acceptsFirstMouse:(NSEvent*)event {
    (void)event;
    return self.acceptFirstMouse;
}
@end

// --- Navigation Restrictions ---

static NSArray* zapp_cached_allowlist = nil;

static BOOL zapp_is_navigation_allowed(NSURL* url) {
    if (!url) return NO;
    NSString* scheme = [[url scheme] lowercaseString];

    // Always allow built-in schemes
    if ([scheme isEqualToString:@"zapp"] || [scheme isEqualToString:@"about"] || [scheme isEqualToString:@"blob"]) {
        return YES;
    }

    // Dev mode: allow localhost
    if (zapp_build_is_dev()) {
        NSString* host = [url host];
        if (host && ([host isEqualToString:@"localhost"] || [host isEqualToString:@"127.0.0.1"])) {
            return YES;
        }
    }

    // User allowlist (parsed once, cached)
    if (!zapp_cached_allowlist) {
        const char* json = app_get_allowed_navigation_json();
        if (json && json[0] != '\0') {
            NSData* data = [[NSString stringWithUTF8String:json] dataUsingEncoding:NSUTF8StringEncoding];
            id parsed = data ? [NSJSONSerialization JSONObjectWithData:data options:0 error:nil] : nil;
            if ([parsed isKindOfClass:[NSArray class]]) {
                zapp_cached_allowlist = parsed;
            }
        }
        if (!zapp_cached_allowlist) {
            zapp_cached_allowlist = @[]; // Empty = no extra patterns
        }
    }

    NSString* urlStr = [url absoluteString];
    for (NSString* pattern in zapp_cached_allowlist) {
        if ([pattern hasSuffix:@"*"]) {
            NSString* prefix = [pattern substringToIndex:pattern.length - 1];
            if ([urlStr hasPrefix:prefix]) return YES;
        } else {
            if ([urlStr isEqualToString:pattern]) return YES;
        }
    }

    return NO;
}

@interface ZappNavigationDelegate : NSObject <WKNavigationDelegate, WKUIDelegate>
@end

@implementation ZappNavigationDelegate
- (void)webView:(WKWebView*)webView decidePolicyForNavigationAction:(WKNavigationAction*)action
    decisionHandler:(void (^)(WKNavigationActionPolicy))handler {
    NSURL* url = action.request.URL;

    if (zapp_is_navigation_allowed(url)) {
        handler(WKNavigationActionPolicyAllow);
        return;
    }

    // Blocked — if user-initiated link click, open in system browser
    if (action.navigationType == WKNavigationTypeLinkActivated) {
        [[NSWorkspace sharedWorkspace] openURL:url];
    }
    handler(WKNavigationActionPolicyCancel);
}

// target="_blank" → open in system browser
- (WKWebView*)webView:(WKWebView*)webView
    createWebViewWithConfiguration:(WKWebViewConfiguration*)config
    forNavigationAction:(WKNavigationAction*)action
    windowFeatures:(WKWindowFeatures*)features {
    (void)config; (void)features;
    NSURL* url = action.request.URL;
    if (url) [[NSWorkspace sharedWorkspace] openURL:url];
    return nil;
}
@end

static ZappNavigationDelegate* zapp_shared_nav_delegate = nil;

// --- App.openExternal ---

void darwin_open_external(const char* url_str) {
    if (!url_str) return;
    NSURL* url = [NSURL URLWithString:[NSString stringWithUTF8String:url_str]];
    if (url) [[NSWorkspace sharedWorkspace] openURL:url];
}

// --- Drag Region ---

// Get WKWebView* for a numeric window ID (from window.m dispatch table)
extern void* darwin_window_get_webview(int32_t window_id);

void darwin_webview_set_drag_region(int32_t window_id, bool drag) {
    void* wv_ptr = darwin_window_get_webview(window_id);
    if (!wv_ptr) return;
    WKWebView* wv = (__bridge WKWebView*)wv_ptr;
    if ([wv isKindOfClass:[ZappWebView class]]) {
        ((ZappWebView*)wv).inDragRegion = drag;
    }
}

// --- WebView Creation ---

void darwin_webview_create(void* window_ptr, bool inspectable, bool accept_first_mouse, const char* url_override) {
    NSWindow* window = (__bridge NSWindow*)window_ptr;
    NSView* hostView = [window contentView];
    NSRect bounds = [hostView bounds];

    WKWebViewConfiguration* config = [[WKWebViewConfiguration alloc] init];
    ZappAssetSchemeHandler* schemeHandler = [[ZappAssetSchemeHandler alloc] init];
    [config setURLSchemeHandler:schemeHandler forURLScheme:@"zapp"];

    WKUserContentController* ucc = [[WKUserContentController alloc] init];
    NSString* ownerId = [NSString stringWithFormat:@"owner-%p", window];
    NSString* windowId = [NSString stringWithFormat:@"win-%p", window];

    // --- Inject user scripts before page load ---

    // 1. App config
    const char* bootstrapName = app_get_bootstrap_name();
    NSString* appName = bootstrapName ? [NSString stringWithUTF8String:bootstrapName] : @"Zapp";
    appName = zapp_escape_js_string([appName UTF8String]);
    BOOL terminate = app_get_bootstrap_application_should_terminate_after_last_window_closed();
    BOOL inspect = app_get_bootstrap_web_content_inspectable();
    int maxWorkers = app_get_bootstrap_max_workers();

    NSString* cspExtra = @"";
    const char* cspRaw = zapp_build_csp();
    if (cspRaw && cspRaw[0] != '\0') {
        NSString* cspStr = zapp_escape_js_string(cspRaw);
        cspExtra = [NSString stringWithFormat:@",csp:'%@'", cspStr];
    }

    NSString* configScript = [NSString stringWithFormat:
        @"(function(){globalThis[Symbol.for('zapp.bootstrapConfig')]="
        "{name:'%@',applicationShouldTerminateAfterLastWindowClosed:%@,"
        "webContentInspectable:%@,maxWorkers:%d%@};})();",
        appName,
        terminate ? @"true" : @"false",
        inspect ? @"true" : @"false",
        maxWorkers, cspExtra];
    [ucc addUserScript:[[WKUserScript alloc] initWithSource:configScript
        injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];

    // 2. Service bindings
    const char* bindingsRaw = service_get_manifest_json();
    NSString* bindingsJson = zapp_escape_js_string(bindingsRaw);
    NSString* bindingsScript = [NSString stringWithFormat:
        @"(function(){globalThis[Symbol.for('zapp.bindingsManifest')]='%@';})();", bindingsJson];
    [ucc addUserScript:[[WKUserScript alloc] initWithSource:bindingsScript
        injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];

    // 3. Owner + window IDs
    NSString* ownerScript = [NSString stringWithFormat:
        @"(function(){globalThis[Symbol.for('zapp.ownerId')]='%@';})();", ownerId];
    [ucc addUserScript:[[WKUserScript alloc] initWithSource:ownerScript
        injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];

    NSString* windowIdScript = [NSString stringWithFormat:
        @"(function(){globalThis[Symbol.for('zapp.windowId')]='%@';})();", windowId];
    [ucc addUserScript:[[WKUserScript alloc] initWithSource:windowIdScript
        injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];

    // 4. Bootstrap script
    const char* bootstrapSrc = zapp_webview_bootstrap_script();
    if (bootstrapSrc) {
        NSString* bootstrap = [NSString stringWithUTF8String:bootstrapSrc];
        [ucc addUserScript:[[WKUserScript alloc] initWithSource:bootstrap
            injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];
    }

    // --- Message handler ---
    ZappMsgHandler* handler = [[ZappMsgHandler alloc] init];
    [ucc addScriptMessageHandler:handler name:@"zapp"];
    [config setUserContentController:ucc];

    // --- Dev tools ---
    if (inspectable) {
        [[config preferences] setValue:@YES forKey:@"developerExtrasEnabled"];
    }

    // --- Create WebView ---
    ZappWebView* webview = [[ZappWebView alloc] initWithFrame:bounds configuration:config];
    webview.acceptFirstMouse = accept_first_mouse ? YES : NO;
    [webview setAutoresizingMask:(NSViewWidthSizable | NSViewHeightSizable)];
    if ([webview respondsToSelector:@selector(setInspectable:)]) {
        [webview setInspectable:inspectable ? YES : NO];
    }

    // Navigation restrictions
    if (!zapp_shared_nav_delegate) {
        zapp_shared_nav_delegate = [[ZappNavigationDelegate alloc] init];
    }
    [webview setNavigationDelegate:zapp_shared_nav_delegate];
    [webview setUIDelegate:(id<WKUIDelegate>)zapp_shared_nav_delegate];

    // Load initial URL (per-window override or default)
    NSURL* url;
    if (url_override && url_override[0] != '\0') {
        url = [NSURL URLWithString:[NSString stringWithUTF8String:url_override]];
    } else {
        url = zapp_initial_url();
    }
    [webview loadRequest:[NSURLRequest requestWithURL:url]];
    [window setContentView:webview];
}

// --- JS evaluation ---

void darwin_webview_eval(void* window_ptr, const char* js) {
    NSWindow* window = (__bridge NSWindow*)window_ptr;
    NSView* content = [window contentView];
    if ([content isKindOfClass:[WKWebView class]]) {
        NSString* script = [NSString stringWithUTF8String:js];
        [(WKWebView*)content evaluateJavaScript:script completionHandler:nil];
    }
}

void darwin_window_load_url(int32_t window_id, const char* url) {
    if (!url) return;
    extern void* darwin_window_get_webview(int32_t numeric_id);
    void* wv_ptr = darwin_window_get_webview(window_id);
    if (!wv_ptr) return;
    WKWebView* wv = (__bridge WKWebView*)wv_ptr;
    NSURL* nsurl = [NSURL URLWithString:[NSString stringWithUTF8String:url]];
    if (nsurl) {
        [wv loadRequest:[NSURLRequest requestWithURL:nsurl]];
    }
}

void darwin_webview_eval_all(const char* js) {
    NSString* script = [NSString stringWithUTF8String:js];
    for (NSWindow* window in [NSApp windows]) {
        NSView* content = [window contentView];
        if ([content isKindOfClass:[WKWebView class]]) {
            [(WKWebView*)content evaluateJavaScript:script completionHandler:nil];
        }
    }
}
