// macOS WebView (WKWebView) implementation — pure Objective-C.
// Custom scheme handler, message handler, bootstrap injection.

#import <Cocoa/Cocoa.h>
#import <WebKit/WebKit.h>
#import "webview.h"

// --- Forward declarations from Zen-C / other .m files ---
extern void* app_get_active(void);

// Build-time config functions (generated by CLI into zapp_build_config.zc)
extern const char* zapp_build_initial_url(void);
extern int zapp_build_use_embedded_assets(void);
extern const char* zapp_build_csp(void);
extern const char* app_get_allowed_navigation_json(void);
extern int zapp_build_is_dev(void);

// Bootstrap script (generated from TS)
extern const char* zapp_webview_bootstrap_script(void);

// App config accessors
extern const char* app_get_bootstrap_name(void);
extern bool app_get_bootstrap_web_content_inspectable(void);
extern bool app_get_bootstrap_application_should_terminate_after_last_window_closed(void);
extern int app_get_bootstrap_max_workers(void);

// Service bindings
extern const char* service_get_manifest_json(void);

// --- Helpers ---

// Single-pass JS string escape — one allocation instead of four.
static NSString* zapp_escape_js_string(const char* raw) {
    if (!raw || raw[0] == '\0') return @"";
    size_t len = strlen(raw);
    // Worst case: every char needs escaping (2x)
    char* buf = (char*)malloc(len * 2 + 1);
    if (!buf) return @"";
    size_t j = 0;
    for (size_t i = 0; i < len; i++) {
        switch (raw[i]) {
            case '\\': buf[j++] = '\\'; buf[j++] = '\\'; break;
            case '\'': buf[j++] = '\\'; buf[j++] = '\''; break;
            case '\n': buf[j++] = '\\'; buf[j++] = 'n'; break;
            case '\r': buf[j++] = '\\'; buf[j++] = 'r'; break;
            default:   buf[j++] = raw[i]; break;
        }
    }
    buf[j] = '\0';
    NSString* result = [NSString stringWithUTF8String:buf];
    free(buf);
    return result;
}

const char* darwin_escape_js_string(const char* raw) {
    return [zapp_escape_js_string(raw) UTF8String];
}

static NSDictionary* zapp_mime_map = nil;

static NSString* zapp_mime_for_path(NSString* path) {
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        zapp_mime_map = @{
            @"html": @"text/html", @"htm": @"text/html",
            @"css": @"text/css", @"js": @"application/javascript",
            @"mjs": @"application/javascript", @"json": @"application/json",
            @"png": @"image/png", @"jpg": @"image/jpeg", @"jpeg": @"image/jpeg",
            @"gif": @"image/gif", @"svg": @"image/svg+xml",
            @"ico": @"image/x-icon", @"woff": @"font/woff",
            @"woff2": @"font/woff2", @"ttf": @"font/ttf",
            @"wasm": @"application/wasm",
        };
    });
    NSString* ext = [[path pathExtension] lowercaseString];
    return zapp_mime_map[ext] ?: @"application/octet-stream";
}

static NSURL* zapp_initial_url(void) {
    const char* configuredUrl = zapp_build_initial_url();
    if (configuredUrl && configuredUrl[0] != '\0') {
        return [NSURL URLWithString:[NSString stringWithUTF8String:configuredUrl]];
    }
    return [NSURL URLWithString:@"zapp://index.html"];
}

// Resolve a user-supplied URL string for Window.create({ url }) or
// window.loadUrl(). If the string lacks a scheme, treat it as relative to
// the current initial URL so apps can pass "#/chat", "?tab=2", or a
// bare path without knowing whether they're in dev (http://localhost:5173)
// or prod (zapp://index.html). Matches RFC 3986 relative-reference
// resolution semantics via NSURL.
static NSURL* zapp_resolve_url(const char* url_cstr) {
    if (!url_cstr || url_cstr[0] == '\0') return zapp_initial_url();
    NSString* s = [NSString stringWithUTF8String:url_cstr];
    if (!s) return zapp_initial_url();

    // Has a scheme separator — absolute URL, use directly.
    if ([s rangeOfString:@"://"].location != NSNotFound) {
        NSURL* absolute = [NSURL URLWithString:s];
        if (absolute) return absolute;
    }

    // Relative — resolve against the initial URL. Covers "#fragment",
    // "?query", "/absolute-path", and "bare-path" per RFC 3986.
    NSURL* base = zapp_initial_url();
    NSURL* resolved = [NSURL URLWithString:s relativeToURL:base];
    if (resolved) return [resolved absoluteURL];

    // Parse failed entirely — fall back to base rather than nil so the
    // webview doesn't stay blank on a typo.
    return base;
}

extern const char* zapp_build_asset_root(void);

static NSString* zapp_asset_root_path(void) {
    // 1. Check build config (set by CLI for prod builds)
    const char* configured = zapp_build_asset_root();
    if (configured && configured[0] != '\0') {
        return [NSString stringWithUTF8String:configured];
    }
    // 2. Check NSBundle resourcePath (for .app bundles)
    NSString* bundleResources = [[NSBundle mainBundle] resourcePath];
    NSString* indexInBundle = [bundleResources stringByAppendingPathComponent:@"index.html"];
    if ([[NSFileManager defaultManager] fileExistsAtPath:indexInBundle]) {
        return bundleResources;
    }
    // 3. Fallback: current working directory (dev mode without .app)
    char cwd[1024];
    if (getcwd(cwd, sizeof(cwd))) {
        return [NSString stringWithUTF8String:cwd];
    }
    return @".";
}

// --- Asset Scheme Handler (zapp://) ---

@interface ZappAssetSchemeHandler : NSObject <WKURLSchemeHandler>
@end

@implementation ZappAssetSchemeHandler
- (void)webView:(WKWebView*)webView startURLSchemeTask:(id<WKURLSchemeTask>)task {
    (void)webView;
    NSURL* url = [task request].URL;
    NSString* host = url.host ?: @"";
    NSString* path = url.path ?: @"/";

    NSString* rel = path;
    if ((rel.length == 0 || [rel isEqualToString:@"/"]) && host.length > 0) {
        rel = [@"/" stringByAppendingString:host];
    } else if (host.length > 0 && ![host isEqualToString:@"app"]) {
        if ([path hasPrefix:@"/assets/"]) rel = path;
    }
    if ([rel isEqualToString:@"/"] || rel.length == 0) rel = @"/index.html";
    while ([rel hasPrefix:@"/"]) rel = [rel substringFromIndex:1];

    // Block path traversal
    if ([rel rangeOfString:@".."].location != NSNotFound) {
        NSHTTPURLResponse* forbidden = [[NSHTTPURLResponse alloc]
            initWithURL:url statusCode:403 HTTPVersion:@"HTTP/1.1"
            headerFields:@{ @"Content-Type": @"text/plain" }];
        [task didReceiveResponse:forbidden];
        [task didReceiveData:[@"Forbidden" dataUsingEncoding:NSUTF8StringEncoding]];
        [task didFinish];
        return;
    }

    // Embedded asset lookup (brotli decompression)
    if (zapp_build_use_embedded_assets()) {
        #ifdef ZAPP_EMBEDDED_ASSET_DEFINED
        extern ZappEmbeddedAsset zapp_embedded_assets[];
        extern int zapp_embedded_assets_count;
        NSString* lookupPath = [@"/" stringByAppendingString:rel];
        for (int i = 0; i < zapp_embedded_assets_count; i++) {
            NSString* assetPath = [NSString stringWithUTF8String:zapp_embedded_assets[i].path];
            if ([assetPath isEqualToString:lookupPath]) {
                NSData* assetData;
                if (zapp_embedded_assets[i].is_brotli && zapp_embedded_assets[i].uncompressed_len > 0) {
                    uint8_t* out = malloc(zapp_embedded_assets[i].uncompressed_len);
                    size_t decoded = compression_decode_buffer(
                        out, zapp_embedded_assets[i].uncompressed_len,
                        zapp_embedded_assets[i].data, zapp_embedded_assets[i].len,
                        NULL, COMPRESSION_BROTLI);
                    assetData = [NSData dataWithBytesNoCopy:out length:decoded freeWhenDone:YES];
                } else {
                    assetData = [NSData dataWithBytes:zapp_embedded_assets[i].data
                                              length:zapp_embedded_assets[i].len];
                }
                NSString* mime = zapp_mime_for_path(rel);
                NSHTTPURLResponse* resp = [[NSHTTPURLResponse alloc]
                    initWithURL:url statusCode:200 HTTPVersion:@"HTTP/1.1"
                    headerFields:@{ @"Content-Type": mime }];
                [task didReceiveResponse:resp];
                [task didReceiveData:assetData];
                [task didFinish];
                return;
            }
        }
        #endif
    }

    // Filesystem fallback (dev mode or asset not found in embedded)
    NSString* assetRoot = zapp_asset_root_path();
    NSString* filePath = [assetRoot stringByAppendingPathComponent:rel];
    NSData* data = [NSData dataWithContentsOfFile:filePath];

    if (!data) {
        NSHTTPURLResponse* notFound = [[NSHTTPURLResponse alloc]
            initWithURL:url statusCode:404 HTTPVersion:@"HTTP/1.1"
            headerFields:@{ @"Content-Type": @"text/plain" }];
        [task didReceiveResponse:notFound];
        [task didReceiveData:[@"Not Found" dataUsingEncoding:NSUTF8StringEncoding]];
        [task didFinish];
        return;
    }

    NSString* mime = zapp_mime_for_path(rel);
    NSHTTPURLResponse* response = [[NSHTTPURLResponse alloc]
        initWithURL:url statusCode:200 HTTPVersion:@"HTTP/1.1"
        headerFields:@{ @"Content-Type": mime, @"Content-Length": [@(data.length) stringValue] }];
    [task didReceiveResponse:response];
    [task didReceiveData:data];
    [task didFinish];
}

- (void)webView:(WKWebView*)webView stopURLSchemeTask:(id<WKURLSchemeTask>)task {
    (void)webView;
    (void)task;
}
@end

// --- Message Handler (JS → Native bridge) ---

@interface ZappMsgHandler : NSObject <WKScriptMessageHandler>
@end

extern int32_t darwin_window_id_for_webview(void* webview);
extern void zapp_handle_message_from_window(void* app, char* msg, int32_t window_id);

@implementation ZappMsgHandler
- (void)userContentController:(WKUserContentController*)ucc didReceiveScriptMessage:(WKScriptMessage*)msg {
    (void)ucc;
    id body = [msg body];
    if (![body isKindOfClass:[NSString class]]) return;
    const char* raw_msg = [(NSString*)body UTF8String];
    if (!raw_msg) return;
    int32_t window_id = darwin_window_id_for_webview((__bridge void*)msg.webView);

    // Fast path: drag region messages are the most frequent (60Hz on mousemove).
    // Detect with simple string prefix check — avoids JSON parse entirely.
    if (raw_msg[0] == '{' && raw_msg[1] == '"' && raw_msg[2] == 't' &&
        raw_msg[3] == '"' && raw_msg[4] == ':' && raw_msg[5] == '4' &&
        strstr(raw_msg, "\"setDragRegion\"") != NULL) {
        BOOL drag = strstr(raw_msg, "\"drag\":true") != NULL;
        extern void darwin_webview_set_drag_region(int32_t window_id, bool drag);
        darwin_webview_set_drag_region(window_id, drag);
        return;
    }

    void* app_ptr = app_get_active();
    if (app_ptr != NULL) {
        zapp_handle_message_from_window(app_ptr, (char*)raw_msg, window_id);
    }
}
@end

// --- WebView Subclass (drag regions, context menu filtering) ---

@interface ZappWebView : WKWebView
@property (nonatomic, assign) BOOL inDragRegion;
@property (nonatomic, assign) BOOL acceptFirstMouse;
@end

@implementation ZappWebView
- (instancetype)initWithFrame:(NSRect)frame configuration:(WKWebViewConfiguration*)config {
    self = [super initWithFrame:frame configuration:config];
    if (self) {
        _inDragRegion = NO;
        _acceptFirstMouse = YES;
    }
    return self;
}
- (void)mouseDown:(NSEvent*)event {
    if (self.inDragRegion) {
        [self.window performWindowDragWithEvent:event];
        return;
    }
    [super mouseDown:event];
}
- (BOOL)mouseDownCanMoveWindow { return self.inDragRegion; }
- (BOOL)acceptsFirstMouse:(NSEvent*)event {
    (void)event;
    return self.acceptFirstMouse;
}
@end

// --- Navigation Restrictions ---

static NSArray* zapp_cached_allowlist = nil;

static BOOL zapp_is_navigation_allowed(NSURL* url) {
    if (!url) return NO;
    NSString* scheme = [[url scheme] lowercaseString];

    // Always allow built-in schemes
    if ([scheme isEqualToString:@"zapp"] || [scheme isEqualToString:@"about"] || [scheme isEqualToString:@"blob"]) {
        return YES;
    }

    // Dev mode: allow localhost
    if (zapp_build_is_dev()) {
        NSString* host = [url host];
        if (host && ([host isEqualToString:@"localhost"] || [host isEqualToString:@"127.0.0.1"])) {
            return YES;
        }
    }

    // User allowlist (parsed once, cached)
    if (!zapp_cached_allowlist) {
        const char* json = app_get_allowed_navigation_json();
        if (json && json[0] != '\0') {
            NSData* data = [[NSString stringWithUTF8String:json] dataUsingEncoding:NSUTF8StringEncoding];
            id parsed = data ? [NSJSONSerialization JSONObjectWithData:data options:0 error:nil] : nil;
            if ([parsed isKindOfClass:[NSArray class]]) {
                zapp_cached_allowlist = parsed;
            }
        }
        if (!zapp_cached_allowlist) {
            zapp_cached_allowlist = @[]; // Empty = no extra patterns
        }
    }

    NSString* urlStr = [url absoluteString];
    for (NSString* pattern in zapp_cached_allowlist) {
        if ([pattern hasSuffix:@"*"]) {
            NSString* prefix = [pattern substringToIndex:pattern.length - 1];
            if ([urlStr hasPrefix:prefix]) return YES;
        } else {
            if ([urlStr isEqualToString:pattern]) return YES;
        }
    }

    return NO;
}

@interface ZappNavigationDelegate : NSObject <WKNavigationDelegate, WKUIDelegate>
@end

@implementation ZappNavigationDelegate

// Auto-show fallback. Primary path is darwin_window_set_bridge_ready
// (fires when the bootstrap script runs at document-start). If the JS
// bootstrap fails to fire for any reason, this catches the window when
// navigation completes so it doesn't stay invisible forever. Whichever
// fires first wins — applyAutoShowOnWindow is idempotent.
- (void)webView:(WKWebView*)webView didFinishNavigation:(WKNavigation*)navigation {
    (void)navigation;
    NSWindow* window = webView.window;
    if (!window) return;
    id delegate = [window delegate];
    if ([delegate respondsToSelector:@selector(applyAutoShowOnWindow:)]) {
        [delegate performSelector:@selector(applyAutoShowOnWindow:) withObject:window];
    }
}

- (void)webView:(WKWebView*)webView decidePolicyForNavigationAction:(WKNavigationAction*)action
    decisionHandler:(void (^)(WKNavigationActionPolicy))handler {
    NSURL* url = action.request.URL;

    if (zapp_is_navigation_allowed(url)) {
        handler(WKNavigationActionPolicyAllow);
        return;
    }

    // Blocked — if user-initiated link click, open in system browser
    if (action.navigationType == WKNavigationTypeLinkActivated) {
        [[NSWorkspace sharedWorkspace] openURL:url];
    }
    handler(WKNavigationActionPolicyCancel);
}

// target="_blank" → open in system browser
- (WKWebView*)webView:(WKWebView*)webView
    createWebViewWithConfiguration:(WKWebViewConfiguration*)config
    forNavigationAction:(WKNavigationAction*)action
    windowFeatures:(WKWindowFeatures*)features {
    (void)config; (void)features;
    NSURL* url = action.request.URL;
    if (url) [[NSWorkspace sharedWorkspace] openURL:url];
    return nil;
}

// DOM <input type="file"> → NSOpenPanel sheet on the owning window.
// Routes through the same panel used by Dialog.openFile so third-party
// libraries (react-dropzone, tiptap, etc.) that emit their own file
// inputs work without app code changes.
- (void)webView:(WKWebView*)webView
    runOpenPanelWithParameters:(WKOpenPanelParameters*)params
    initiatedByFrame:(WKFrameInfo*)frame
    completionHandler:(void (^)(NSArray<NSURL*>* _Nullable))handler {
    (void)frame;
    NSOpenPanel* panel = [NSOpenPanel openPanel];
    panel.canChooseFiles = YES;
    panel.canChooseDirectories = params.allowsDirectories;
    panel.allowsMultipleSelection = params.allowsMultipleSelection;

    // Best-effort translation of HTML accept="..." — WebKit exposes the
    // parsed extensions as a private KVC key. If unavailable, show all
    // file types rather than failing.
    @try {
        id exts = [params valueForKey:@"_acceptedFileExtensions"];
        if ([exts isKindOfClass:[NSArray class]] && [exts count] > 0) {
            panel.allowedFileTypes = exts;
        }
    } @catch (NSException* ignored) { (void)ignored; }

    NSWindow* parent = webView.window;
    void (^finish)(NSModalResponse) = ^(NSModalResponse response) {
        handler(response == NSModalResponseOK ? panel.URLs : nil);
    };
    if (parent) {
        [panel beginSheetModalForWindow:parent completionHandler:finish];
    } else {
        finish([panel runModal]);
    }
}
@end

static ZappNavigationDelegate* zapp_shared_nav_delegate = nil;

// --- App / shell helpers ---
//
// Each helper main-thread-bounces because NSWorkspace's UI-affecting
// methods (activateFileViewerSelectingURLs, openURL — the latter
// trips assertions when invoked off-main on macOS 26.x) require it.
// Callers may be webview, worker, or service contexts; trampolining
// here means no caller has to think about it. Same pattern as the
// alpha.31 fix to darwin_webview_eval_all.

void darwin_open_external(const char* url_str) {
    if (!url_str || !url_str[0]) return;
    NSURL* url = [NSURL URLWithString:[NSString stringWithUTF8String:url_str]];
    if (!url) return;
    void (^run)(void) = ^{ [[NSWorkspace sharedWorkspace] openURL:url]; };
    if ([NSThread isMainThread]) run();
    else dispatch_async(dispatch_get_main_queue(), run);
}

// Reveal a file or folder in Finder with the item selected. For a
// folder, Finder opens the *parent* and selects the folder; pass the
// folder's contents path if you want the folder itself opened.
void darwin_show_item_in_folder(const char* path) {
    if (!path || !path[0]) return;
    NSString* nsPath = [NSString stringWithUTF8String:path];
    if (!nsPath) return;
    NSURL* url = [NSURL fileURLWithPath:nsPath];
    if (!url) return;
    void (^run)(void) = ^{
        [[NSWorkspace sharedWorkspace] activateFileViewerSelectingURLs:@[url]];
    };
    if ([NSThread isMainThread]) run();
    else dispatch_async(dispatch_get_main_queue(), run);
}

// Open a file or folder using the system default application.
// Files: launches the default app (TextEdit for .txt, Preview for
// .png, etc.). Folders: opens in Finder. URLs with schemes go through
// darwin_open_external instead — this is filesystem-paths-only.
void darwin_open_path(const char* path) {
    if (!path || !path[0]) return;
    NSString* nsPath = [NSString stringWithUTF8String:path];
    if (!nsPath) return;
    NSURL* url = [NSURL fileURLWithPath:nsPath];
    if (!url) return;
    void (^run)(void) = ^{ [[NSWorkspace sharedWorkspace] openURL:url]; };
    if ([NSThread isMainThread]) run();
    else dispatch_async(dispatch_get_main_queue(), run);
}

// Move a file or folder to the user's Trash. Reversible via Finder's
// "Put Back". Silent on failure (path missing, permission denied) —
// callers wanting to know if it worked should fs.exists() afterward.
void darwin_trash_item(const char* path) {
    if (!path || !path[0]) return;
    NSString* nsPath = [NSString stringWithUTF8String:path];
    if (!nsPath) return;
    NSURL* url = [NSURL fileURLWithPath:nsPath];
    if (!url) return;
    void (^run)(void) = ^{
        [[NSFileManager defaultManager] trashItemAtURL:url
                                      resultingItemURL:nil error:nil];
    };
    if ([NSThread isMainThread]) run();
    else dispatch_async(dispatch_get_main_queue(), run);
}

// --- Drag Region ---

// Get WKWebView* for a numeric window ID (from window.m dispatch table)
extern void* darwin_window_get_webview(int32_t window_id);

void darwin_webview_set_drag_region(int32_t window_id, bool drag) {
    void* wv_ptr = darwin_window_get_webview(window_id);
    if (!wv_ptr) return;
    WKWebView* wv = (__bridge WKWebView*)wv_ptr;
    if ([wv isKindOfClass:[ZappWebView class]]) {
        ((ZappWebView*)wv).inDragRegion = drag;
    }
}

// --- WebView Creation ---

void darwin_webview_create(void* window_ptr, bool inspectable, bool accept_first_mouse,
                           const char* url_override, int32_t numeric_id_pre_alloc) {
    NSWindow* window = (__bridge NSWindow*)window_ptr;
    NSView* hostView = [window contentView];
    NSRect bounds = [hostView bounds];

    WKWebViewConfiguration* config = [[WKWebViewConfiguration alloc] init];
    ZappAssetSchemeHandler* schemeHandler = [[ZappAssetSchemeHandler alloc] init];
    [config setURLSchemeHandler:schemeHandler forURLScheme:@"zapp"];

    WKUserContentController* ucc = [[WKUserContentController alloc] init];
    NSString* ownerId = [NSString stringWithFormat:@"owner-%p", window];
    // Bake the canonical "win-<N>" id into the bootstrap user script so
    // module-top `Window.current()` resolves correctly. Caller passes
    // the pre-allocated numeric id from WindowManager. -1 = no id yet;
    // we leave the symbol unset and let darwin_window_register_numeric_id
    // fix it via eval (works for the rare internal-construction paths).
    NSString* windowId = (numeric_id_pre_alloc >= 0)
        ? [NSString stringWithFormat:@"win-%d", numeric_id_pre_alloc]
        : @"";

    // --- Inject user scripts before page load ---

    // 1. App config
    const char* bootstrapName = app_get_bootstrap_name();
    NSString* appName = bootstrapName ? [NSString stringWithUTF8String:bootstrapName] : @"Zapp";
    appName = zapp_escape_js_string([appName UTF8String]);
    BOOL terminate = app_get_bootstrap_application_should_terminate_after_last_window_closed();
    BOOL inspect = app_get_bootstrap_web_content_inspectable();
    int maxWorkers = app_get_bootstrap_max_workers();

    NSString* cspExtra = @"";
    const char* cspRaw = zapp_build_csp();
    if (cspRaw && cspRaw[0] != '\0') {
        NSString* cspStr = zapp_escape_js_string(cspRaw);
        cspExtra = [NSString stringWithFormat:@",csp:'%@'", cspStr];
    }

    // theme: initial appearance at window-create time. App.getTheme() reads
    // this on import, then refreshes from app:theme-changed events. Without
    // the initial value, the first render in dark mode would briefly assume
    // "light" until the first KVO fire — visible flash.
    extern const char* darwin_get_theme(void);
    const char* themeC = darwin_get_theme();
    NSString* themeStr = [NSString stringWithUTF8String:themeC ? themeC : "light"];

    NSString* configScript = [NSString stringWithFormat:
        @"(function(){globalThis[Symbol.for('zapp.bootstrapConfig')]="
        "{name:'%@',applicationShouldTerminateAfterLastWindowClosed:%@,"
        "webContentInspectable:%@,maxWorkers:%d,theme:'%@'%@};})();",
        appName,
        terminate ? @"true" : @"false",
        inspect ? @"true" : @"false",
        maxWorkers, themeStr, cspExtra];
    [ucc addUserScript:[[WKUserScript alloc] initWithSource:configScript
        injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];

    // 2. Service bindings
    const char* bindingsRaw = service_get_manifest_json();
    NSString* bindingsJson = zapp_escape_js_string(bindingsRaw);
    NSString* bindingsScript = [NSString stringWithFormat:
        @"(function(){globalThis[Symbol.for('zapp.bindingsManifest')]='%@';})();", bindingsJson];
    [ucc addUserScript:[[WKUserScript alloc] initWithSource:bindingsScript
        injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];

    // 3. Owner + window IDs (window id baked from the pre-allocated
    //    numeric id, so module-top Window.current() resolves correctly
    //    without waiting for darwin_window_register_numeric_id).
    NSString* ownerScript = [NSString stringWithFormat:
        @"(function(){globalThis[Symbol.for('zapp.ownerId')]='%@';})();", ownerId];
    [ucc addUserScript:[[WKUserScript alloc] initWithSource:ownerScript
        injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];

    if (windowId.length > 0) {
        NSString* windowIdScript = [NSString stringWithFormat:
            @"(function(){globalThis[Symbol.for('zapp.windowId')]='%@';})();", windowId];
        [ucc addUserScript:[[WKUserScript alloc] initWithSource:windowIdScript
            injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];
    }

    // 4. Window metrics — expose native values as CSS custom properties so
    //    custom-titlebar apps don't have to eyeball 28px / 78px guesses.
    //    - --zapp-titlebar-height: vertical inset taken by the native
    //      titlebar (0 on truly borderless windows).
    //    - --zapp-content-inset-left: horizontal distance from the window's
    //      left edge to the right side of the zoom (green) standard button,
    //      plus a small pad. Apps pad their content by this amount so the
    //      traffic lights don't overlap their own UI.
    //    - data-zapp-titlebar-style on <html>: "default" | "hidden" |
    //      "hiddenInset", for style-conditional CSS.
    {
        CGFloat titlebarHeight = window.frame.size.height - window.contentLayoutRect.size.height;
        if (titlebarHeight < 0) titlebarHeight = 0;

        CGFloat contentInsetLeft = 0;
        NSButton* zoomBtn = [window standardWindowButton:NSWindowZoomButton];
        if (zoomBtn) {
            contentInsetLeft = NSMaxX(zoomBtn.frame) + 8.0; // 8pt pad past rightmost button
        }

        // Derive style name from the window's actual state rather than
        // re-plumbing the original WindowOptions enum.
        NSString* styleName = @"default";
        if ([window titleVisibility] == NSWindowTitleHidden &&
            ([window styleMask] & NSWindowStyleMaskFullSizeContentView)) {
            styleName = contentInsetLeft > 0 ? @"hiddenInset" : @"hidden";
        }

        NSString* metricsScript = [NSString stringWithFormat:
            @"(function(){try{var r=document.documentElement;"
            @"if(r){r.style.setProperty('--zapp-titlebar-height','%.0fpx');"
            @"r.style.setProperty('--zapp-content-inset-left','%.0fpx');"
            @"r.setAttribute('data-zapp-titlebar-style','%@');}}catch(e){}})();",
            titlebarHeight, contentInsetLeft, styleName];
        [ucc addUserScript:[[WKUserScript alloc] initWithSource:metricsScript
            injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];
    }

    // 5. Bootstrap script
    const char* bootstrapSrc = zapp_webview_bootstrap_script();
    if (bootstrapSrc) {
        NSString* bootstrap = [NSString stringWithUTF8String:bootstrapSrc];
        [ucc addUserScript:[[WKUserScript alloc] initWithSource:bootstrap
            injectionTime:WKUserScriptInjectionTimeAtDocumentStart forMainFrameOnly:NO]];
    }

    // --- Message handler ---
    ZappMsgHandler* handler = [[ZappMsgHandler alloc] init];
    [ucc addScriptMessageHandler:handler name:@"zapp"];
    [config setUserContentController:ucc];

    // --- Dev tools ---
    if (inspectable) {
        [[config preferences] setValue:@YES forKey:@"developerExtrasEnabled"];
    }

    // --- Create WebView ---
    ZappWebView* webview = [[ZappWebView alloc] initWithFrame:bounds configuration:config];
    webview.acceptFirstMouse = accept_first_mouse ? YES : NO;
    [webview setAutoresizingMask:(NSViewWidthSizable | NSViewHeightSizable)];
    if ([webview respondsToSelector:@selector(setInspectable:)]) {
        [webview setInspectable:inspectable ? YES : NO];
    }
    // Color the WKWebView's own background so it doesn't paint white
    // before first content frame. underPageBackgroundColor (macOS 12+)
    // is the canonical knob — it controls what WebKit renders behind
    // page content during navigation, before first paint, and during
    // scroll bounce. Like windowBackgroundColor, it's a dynamic NSColor
    // that resolves correctly across light/dark mode without observation.
    if ([webview respondsToSelector:@selector(setUnderPageBackgroundColor:)]) {
        [webview setUnderPageBackgroundColor:[NSColor windowBackgroundColor]];
    }

    // Navigation restrictions
    if (!zapp_shared_nav_delegate) {
        zapp_shared_nav_delegate = [[ZappNavigationDelegate alloc] init];
    }
    [webview setNavigationDelegate:zapp_shared_nav_delegate];
    [webview setUIDelegate:(id<WKUIDelegate>)zapp_shared_nav_delegate];

    // Load initial URL (per-window override or default). url_override is
    // resolved relative to the initial URL when it lacks a scheme, so
    // Window.create({ url: "#/chat" }) works from either webview or worker
    // without the caller knowing dev vs prod URL base.
    NSURL* url = (url_override && url_override[0] != '\0')
        ? zapp_resolve_url(url_override)
        : zapp_initial_url();
    [webview loadRequest:[NSURLRequest requestWithURL:url]];
    [window setContentView:webview];
}

// --- JS evaluation ---
//
// All three helpers below touch WKWebView APIs that are documented
// main-thread-only (evaluateJavaScript:, loadRequest:, iterating
// [NSApp windows]). Callers include workers firing Events.emit at high
// rates (e.g. streaming large payloads, WebSocket receive loops) — from
// those threads, calling these APIs directly is undefined behavior that
// usually "works" but intermittently trips WebKit ProcessThrottler
// invariants under load (EXC_BREAKPOINT brk 1 on macOS 26.x).
//
// Bounce to main when not already there. NSString is created up-front
// (off the critical path) and captured into the block; dispatch_async
// retains it through execution.

void darwin_webview_eval(void* window_ptr, const char* js) {
    if (!window_ptr || !js) return;
    NSWindow* window = (__bridge NSWindow*)window_ptr;
    NSString* script = [NSString stringWithUTF8String:js];
    if (!script) return;
    void (^run)(void) = ^{
        NSView* content = [window contentView];
        if ([content isKindOfClass:[WKWebView class]]) {
            [(WKWebView*)content evaluateJavaScript:script completionHandler:nil];
        }
    };
    if ([NSThread isMainThread]) run();
    else dispatch_async(dispatch_get_main_queue(), run);
}

void darwin_window_load_url(int32_t window_id, const char* url) {
    if (!url) return;
    extern void* darwin_window_get_webview(int32_t numeric_id);
    void* wv_ptr = darwin_window_get_webview(window_id);
    if (!wv_ptr) return;
    WKWebView* wv = (__bridge WKWebView*)wv_ptr;
    // Same relative-URL rules as Window.create({ url }) — "#/chat" et al.
    // resolve against the initial URL rather than failing to parse.
    NSURL* nsurl = zapp_resolve_url(url);
    if (!nsurl) return;
    void (^run)(void) = ^{
        [wv loadRequest:[NSURLRequest requestWithURL:nsurl]];
    };
    if ([NSThread isMainThread]) run();
    else dispatch_async(dispatch_get_main_queue(), run);
}

void darwin_webview_eval_all(const char* js) {
    if (!js) return;
    NSString* script = [NSString stringWithUTF8String:js];
    if (!script) return;
    void (^run)(void) = ^{
        for (NSWindow* window in [NSApp windows]) {
            NSView* content = [window contentView];
            if ([content isKindOfClass:[WKWebView class]]) {
                [(WKWebView*)content evaluateJavaScript:script completionHandler:nil];
            }
        }
    };
    if ([NSThread isMainThread]) run();
    else dispatch_async(dispatch_get_main_queue(), run);
}
