import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";

type ServiceMethod = {
  name: string;
  args: { name: string; type: string }[];
  returnType: string;
};

type ServiceDef = {
  name: string;
  methods: ServiceMethod[];
};

const ZEN_TO_TS_TYPES: Record<string, string> = {
  string: "string",
  int: "number",
  float: "number",
  double: "number",
  bool: "boolean",
  void: "void",
};

function mapType(zenType: string): string {
  return ZEN_TO_TS_TYPES[zenType.trim()] ?? "unknown";
}

/**
 * Scans .zc files for service_add registrations and extracts method signatures.
 *
 * Looks for patterns like:
 *   app.service.add("name", handler_fn);
 *
 * Then finds the corresponding function definition:
 *   fn handler_fn(app: App*, args: string) -> string { ... }
 */
async function scanServices(srcDir: string): Promise<ServiceDef[]> {
  const services: ServiceDef[] = [];
  const files: string[] = [];

  async function walk(dir: string) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name.startsWith(".") || entry.name === "vendor") continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (entry.name.endsWith(".zc")) {
        files.push(full);
      }
    }
  }

  await walk(srcDir);

  const allContent: { file: string; content: string }[] = [];
  for (const file of files) {
    const content = await fs.readFile(file, "utf8");
    allContent.push({ file, content });
  }

  // Find service.add("name", handler) registrations
  const addPattern = /\.service\.add\(\s*"([^"]+)"\s*,\s*(\w+)\s*\)/g;
  const registrations: { serviceName: string; handlerName: string }[] = [];

  for (const { content } of allContent) {
    let match;
    while ((match = addPattern.exec(content)) !== null) {
      registrations.push({ serviceName: match[1], handlerName: match[2] });
    }
  }

  // For each registration, find the function signature
  for (const { serviceName, handlerName } of registrations) {
    const fnPattern = new RegExp(
      `fn\\s+${handlerName}\\s*\\(([^)]*)\\)\\s*->\\s*(\\w+)`,
    );

    let found = false;
    for (const { content } of allContent) {
      const fnMatch = fnPattern.exec(content);
      if (!fnMatch) continue;

      const rawArgs = fnMatch[1];
      const returnType = mapType(fnMatch[2]);

      const args: { name: string; type: string }[] = [];
      for (const part of rawArgs.split(",")) {
        const trimmed = part.trim();
        if (!trimmed) continue;
        const [name, type] = trimmed.split(":").map((s) => s.trim());
        if (name === "app" || type === "App*") continue;
        args.push({ name, type: mapType(type) });
      }

      services.push({
        name: serviceName,
        methods: [{ name: serviceName, args, returnType }],
      });
      found = true;
      break;
    }

    if (!found) {
      process.stderr.write(
        `[zapp] warning: could not find function '${handlerName}' for service '${serviceName}'\n`,
      );
    }
  }

  return services;
}

function generateBindingFile(service: ServiceDef): string {
  const lines: string[] = [
    `// Auto-generated by \`zapp generate\`. Do not edit.`,
    `import { Services } from "@zapp/runtime";`,
    ``,
  ];

  const className = service.name.charAt(0).toUpperCase() + service.name.slice(1);

  lines.push(`export class ${className} {`);
  for (const method of service.methods) {
    const params = method.args
      .map((a) => `${a.name}: ${a.type}`)
      .join(", ");
    const argsExpr = method.args.length === 0
      ? "{}"
      : method.args.length === 1
        ? method.args[0].name
        : `{ ${method.args.map((a) => a.name).join(", ")} }`;

    lines.push(
      `  static async ${method.name}(${params}): Promise<${method.returnType}> {`,
    );
    lines.push(
      `    return Services.invoke<${method.returnType}>("${method.name}", ${argsExpr});`,
    );
    lines.push(`  }`);
  }
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

export async function runGenerate({
  root,
  outDir,
  frontendDir,
}: {
  root: string;
  outDir?: string;
  frontendDir?: string;
}) {
  const base = frontendDir ?? root;
  const srcDir = path.join(base, "src");
  const hasSrcDir = await fs.stat(srcDir).then(() => true, () => false);
  const targetDir = outDir
    ? path.resolve(root, outDir)
    : path.join(hasSrcDir ? srcDir : base, "generated");

  process.stdout.write(`[zapp] scanning for service registrations...\n`);
  const zappDir = path.join(root, "zapp");
  const scanDir = await fs.stat(zappDir).then(() => zappDir, () => root);
  const services = await scanServices(scanDir);

  if (services.length === 0) {
    process.stdout.write(
      `[zapp] no service registrations found. Nothing to generate.\n`,
    );
    return;
  }

  await fs.mkdir(targetDir, { recursive: true });

  const indexExports: string[] = [];
  for (const service of services) {
    const className =
      service.name.charAt(0).toUpperCase() + service.name.slice(1);
    const fileName = `${className}.ts`;
    const filePath = path.join(targetDir, fileName);
    const content = generateBindingFile(service);
    await fs.writeFile(filePath, content, "utf8");
    process.stdout.write(`[zapp] generated ${path.relative(root, filePath)}\n`);
    indexExports.push(`export { ${className} } from "./${className}";`);
  }

  const indexPath = path.join(targetDir, "index.ts");
  await fs.writeFile(
    indexPath,
    `// Auto-generated by \`zapp generate\`. Do not edit.\n${indexExports.join("\n")}\n`,
    "utf8",
  );
  process.stdout.write(
    `[zapp] generated ${services.length} binding(s) in ${path.relative(root, targetDir)}/\n`,
  );
}
