// Generates .zapp/ build artifacts:
// - zapp_build_config.zc — build-time constants
// - zapp_platform.zc — platform .m file compilation directives

import path from "node:path";
import { mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import type { ResolvedConfig } from "./config";
import { resolveNativeDir, getPlatformSources } from "./native";

interface BuildConfigOptions {
  root: string;
  config: ResolvedConfig;
  mode: "dev" | "prod";
  devUrl?: string;
  embedAssets?: boolean;
}

export async function generateBuildConfig(opts: BuildConfigOptions): Promise<string> {
  const { root, config, mode, devUrl, embedAssets } = opts;
  const zappDir = path.join(root, ".zapp");
  await mkdir(zappDir, { recursive: true });

  const isDev = mode === "dev";
  const initialUrl = isDev && devUrl ? devUrl : "";
  const assetRoot = isDev ? "" : path.resolve(root, config.assetDir);
  const devTools = isDev ? 1 : 0;
  const logLevel = isDev ? "debug" : "warn";

  // Escape allowNavigation patterns for C string
  const allowNav = config.security?.allowNavigation;
  const allowNavJson = allowNav && allowNav.length > 0
    ? JSON.stringify(allowNav).replace(/\\/g, "\\\\").replace(/"/g, '\\"')
    : "";

  const content = `// AUTO-GENERATED by zapp CLI. Do not edit.

fn zapp_build_initial_url() -> string { return "${initialUrl}"; }
fn zapp_build_asset_root() -> string { return "${assetRoot}"; }
fn zapp_build_use_embedded_assets() -> int { return ${embedAssets ? 1 : 0}; }
fn zapp_build_csp() -> string { return ""; }
fn zapp_build_dev_tools_default() -> int { return ${devTools}; }
fn zapp_build_log_level() -> string { return "${logLevel}"; }
fn zapp_build_allowed_navigation() -> string { raw { return "${allowNavJson}"; } return ""; }
fn zapp_build_is_dev() -> int { return ${isDev ? 1 : 0}; }
fn zapp_build_accept_first_mouse() -> int { return ${config.macos?.acceptFirstMouse === false ? 0 : 1}; }
`;

  const outPath = path.join(zappDir, "zapp_build_config.zc");
  await Bun.write(outPath, content);
  return outPath;
}

// Generate .zapp/zapp_platform.zc with .m file cflags
export async function generatePlatformConfig(root: string, buildFile?: string): Promise<string> {
  const zappDir = path.join(root, ".zapp");
  await mkdir(zappDir, { recursive: true });

  const nativeDir = resolveNativeDir();
  const sources = getPlatformSources(nativeDir);

  let content = "// AUTO-GENERATED by zapp CLI. Do not edit.\n// Platform-specific compilation sources.\n\n";

  if (process.platform === "darwin" && sources.length > 0) {
    content += `//> macos: cflags: ${sources.join(" ")}\n`;
  }

  // Check if txiki.js workers are enabled (user has ZAPP_WORKER_ENGINE_TXIKI in build.zc)
  let hasTxiki = false;
  const userBuild = buildFile ?? path.join(root, "zapp", "build.zc");
  try {
    const content = await Bun.file(userBuild).text();
    hasTxiki = content.includes("ZAPP_WORKER_ENGINE_TXIKI");
  } catch {}
  if (hasTxiki) {
    const txikiC = path.join(nativeDir, "worker", "engines", "txiki.c");
    if (existsSync(txikiC)) sources.push(txikiC);
  }
  if (hasTxiki) {
    // Find txiki.js vendor dir (sibling to native/)
    const txikiDir = path.resolve(nativeDir, "../vendor/txiki.js");
    if (existsSync(path.join(txikiDir, "src", "tjs.h"))) {
      content += `//> cflags: -I${path.join(txikiDir, "src")} -I${path.join(txikiDir, "deps", "quickjs")} -I${path.join(txikiDir, "deps", "libuv", "include")}\n`;
    }
  }

  if (process.platform === "win32" && sources.length > 0) {
    // WebView2 SDK include path (self-contained loader — no WebView2Loader.dll needed)
    const webview2Dir = path.resolve(nativeDir, "../vendor/webview2");
    const webview2Include = path.join(webview2Dir, "include");
    content += `//> windows: cflags: ${sources.join(" ")} -I${webview2Include}\n`;
  }

  const outPath = path.join(zappDir, "zapp_platform.zc");
  await Bun.write(outPath, content);
  return outPath;
}
