// Generates .zapp/ build artifacts:
// - zapp_build_config.zc — build-time constants
// - zapp_platform.zc — platform .m file compilation directives

import path from "node:path";
import { mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolvePlatformValue, type ResolvedConfig } from "./config";
import { getPlatformSources, getUserProjectSources, type BuildTarget, detectTarget, isIOSTarget } from "./native";
import { resolveNativeDir, resolveVendorDir } from "./paths";

// xcrun-resolved iOS SDK paths. Cached for the life of the CLI process
// — calling xcrun is ~80ms, called only once per build now.
const sdkPathCache = new Map<string, string>();
async function resolveSDKPath(sdk: "iphonesimulator" | "iphoneos"): Promise<string> {
  const cached = sdkPathCache.get(sdk);
  if (cached) return cached;
  const proc = Bun.spawn(["xcrun", "--sdk", sdk, "--show-sdk-path"], {
    stdout: "pipe", stderr: "pipe",
  });
  const out = (await new Response(proc.stdout).text()).trim();
  const exit = await proc.exited;
  if (exit !== 0 || !out) {
    throw new Error(
      `[zapp] couldn't resolve ${sdk} SDK path via xcrun (exit ${exit}). ` +
      `Make sure Xcode + Command Line Tools are installed, then run ` +
      `\`xcodebuild -runFirstLaunch\` and \`sudo xcode-select --install\`.`
    );
  }
  sdkPathCache.set(sdk, out);
  return out;
}

interface BuildConfigOptions {
  root: string;
  config: ResolvedConfig;
  mode: "dev" | "prod";
  devUrl?: string;
  embedAssets?: boolean;
}

export async function generateBuildConfig(opts: BuildConfigOptions): Promise<string> {
  const { root, config, mode, devUrl, embedAssets } = opts;
  const zappDir = path.join(root, ".zapp");
  await mkdir(zappDir, { recursive: true });

  const isDev = mode === "dev";
  const initialUrl = isDev && devUrl ? devUrl : "";
  const assetRoot = isDev ? "" : path.resolve(root, config.assetDir);
  const devTools = isDev ? 1 : 0;

  // Runtime policies (acceptFirstMouse, allowNavigation) moved to Zen-C
  // — see WindowOptions.acceptFirstMouse and App.security.allow_navigation.
  // zapp_build_log_level was dead, removed.

  // Filesystem allowlist — emitted as a JSON array literal. The native
  // fs.zc parses this once at startup and prefix-matches every FS call
  // against it. Empty array = FS is fully locked down (every call
  // denied), which is the correct default if the user hasn't opted in.
  const fsAllow = config.fs?.allow ?? [];
  const fsAllowJson = JSON.stringify(fsAllow).replace(/"/g, '\\"');
  const fsPersistGrants = config.fs?.persistDialogGrants ? "true" : "false";

  // Custom protocols (G19) — declared schemes registered as
  // WKURLSchemeHandlers on every webview. Each scheme name must be
  // a valid URL scheme (lowercase letters / digits / -). Validation
  // is permissive here; WKWebView will reject reserved schemes
  // (http/https/ws/wss/zapp/about/etc.) at the setURLSchemeHandler
  // call with a thrown NSException.
  const protocols = (config.protocols ?? []).filter(s => /^[a-z][a-z0-9.+-]*$/.test(s));
  const protocolsJson = JSON.stringify(protocols).replace(/"/g, '\\"');

  // Webview preferences. Tri-state encoding for booleans so the
  // platform-side code can distinguish "user explicitly set false"
  // from "user didn't touch it" — preserves the WKWebView default
  // when the field is omitted, applies the explicit value when set.
  //   unset → -1   false → 0   true → 1
  // minimumFontSize: -1 when unset, the requested value otherwise.
  const wp = config.webviewPreferences ?? {};
  const tri = (v: boolean | undefined): number =>
    v === undefined ? -1 : (v ? 1 : 0);
  const wpAutoplay  = tri(wp.autoplayWithoutUserGesture);
  const wpBackFwd   = tri(wp.backForwardNavigationGestures);
  const wpTextIA    = tri(wp.textInteractionEnabled);
  const wpMinFont   = wp.minimumFontSize === undefined
    ? -1
    : Math.max(0, Math.round(wp.minimumFontSize));

  const content = `// AUTO-GENERATED by zapp CLI. Do not edit.

fn zapp_build_initial_url() -> string { return "${initialUrl}"; }
fn zapp_build_asset_root() -> string { return "${assetRoot}"; }
fn zapp_build_use_embedded_assets() -> int { return ${embedAssets ? 1 : 0}; }
fn zapp_build_csp() -> string { return ""; }
fn zapp_build_dev_tools_default() -> int { return ${devTools}; }
fn zapp_build_is_dev() -> int { return ${isDev ? 1 : 0}; }
fn zapp_build_fs_allowlist_json() -> string { return "${fsAllowJson}"; }
fn zapp_build_fs_persist_grants() -> bool { return ${fsPersistGrants}; }
fn zapp_build_custom_protocols_json() -> string { return "${protocolsJson}"; }
fn zapp_build_webview_autoplay_without_user_gesture() -> int { return ${wpAutoplay}; }
fn zapp_build_webview_back_forward_gestures() -> int { return ${wpBackFwd}; }
fn zapp_build_webview_text_interaction_enabled() -> int { return ${wpTextIA}; }
fn zapp_build_webview_minimum_font_size() -> int { return ${wpMinFont}; }
`;

  const outPath = path.join(zappDir, "zapp_build_config.zc");
  await Bun.write(outPath, content);
  return outPath;
}

// Generate .zapp/zapp_headless_workers.zc — the function native/app/app.zc
// declares as `extern fn zapp_start_headless_workers()`. Body contains one
// call per entry in zappConfig.headless; empty body when no headless workers
// are configured.
// String → ZAPP_ENGINE_* numeric ID matching native/worker/registry.zc.
// Mirror of the constants there so the generated headless-worker
// invocations pass the right integer per engine.
// -1 means "let the resolver pick the first available engine."
function engineNameToId(name: string | undefined): number {
  switch (name) {
    case "bare-jsc":     return 2;
    case "bare-v8":      return 3;
    case "bare-quickjs": return 4;
    case "bare-mqjs":    return 5;
    case "bare-hermes":  return 6;
    case "zjs":          return 7;
    default:             return -1;
  }
}

export async function generateHeadlessWorkers(opts: {
  root: string;
  headless?: Record<string, string | {
    script: string;
    restart?: { maxRetries?: number; withinMs?: number } | false;
    engine?: "bare-jsc" | "bare-v8" | "bare-quickjs" | "bare-mqjs" | "bare-hermes" | "zjs";
    bytecode?: boolean;  // type-narrowed at the user-facing HeadlessWorkerConfig boundary
  }>;
}): Promise<string> {
  const { root, headless } = opts;
  const zappDir = path.join(root, ".zapp");
  await mkdir(zappDir, { recursive: true });

  const entries = Object.entries(headless ?? {});
  const calls = entries
    .map(([id, value]) => {
      // Bare string → no engine, no restart policy, no bytecode.
      if (typeof value === "string") {
        const url = `/_workers/_headless_${id}.mjs`;
        return `    zapp_start_headless_worker("h-${id}", "${url}");`;
      }
      // Object form. Pull engine + restart + bytecode.
      const engineId = engineNameToId(value.engine);
      const restart = value.restart;
      const max = restart ? (restart.maxRetries ?? 3) : 0;
      const within = restart ? (restart.withinMs ?? 60_000) : 0;
      // bytecode: true is only meaningful for zjs. The CLI build step
      // produces a sibling .zbc file via `zjs compile`; the engine
      // detects the extension and dispatches to zjs_eval_bytecode.
      if (value.bytecode && value.engine !== "zjs") {
        throw new Error(
          `[zapp] headless worker "${id}": \`bytecode: true\` is only supported for ` +
          `\`engine: "zjs"\` (got \`engine: "${value.engine}"\`).`
        );
      }
      const ext = value.bytecode ? "zbc" : "mjs";
      const url = `/_workers/_headless_${id}.${ext}`;
      return `    zapp_start_headless_worker_full("h-${id}", "${url}", ${engineId}, ${max}, ${within});`;
    })
    .join("\n");

  const body = calls || `    // No headless workers configured.`;

  const content = `// AUTO-GENERATED by zapp CLI. Do not edit.
// Implementation for native/app/app.zc's extern fn zapp_start_headless_workers().

fn zapp_start_headless_workers() -> void {
${body}
}
`;

  const outPath = path.join(zappDir, "zapp_headless_workers.zc");
  await Bun.write(outPath, content);
  return outPath;
}

/**
 * For iOS targets: generate a substitute build.zc that strips the
 * user's `//> macos: ...` directives (zc applies them based on host
 * platform, not build target — so without this they pull in
 * Cocoa.framework for iOS builds and link fails with "framework Cocoa
 * not found"). Imports / defines / pragmas the user wrote outside the
 * `macos:` prefix carry through unchanged.
 *
 * Also injects the iOS-needed defines (apple, ZAPP_WORKER_ENGINE_*)
 * since the user's `macos:` versions of those just got stripped.
 *
 * Engine selection is taken from BOTH the user's build.zc declarations
 * AND `zapp.config.ts` headless entries' `engine:` field. The latter
 * is the modern path — without it, a config-only engine (e.g.
 * `engine: "zjs"`) would silently fall back to the bare-jsc default
 * because the iOS overlay used to only look at build.zc text.
 */
export async function generateIOSBuildFile(
  root: string,
  originalBuildFile: string,
  config?: ResolvedConfig,
): Promise<string> {
  void root;
  let content = "";
  try {
    content = await Bun.file(originalBuildFile).text();
  } catch { content = ""; }

  // Strip uncommented `//> macos: ...` lines. We KEEP `// //> macos: ...`
  // (still commented) lines so the generated file is human-readable
  // when debugging.
  const filtered = content
    .split("\n")
    .filter(line => !/^\/\/>\s*macos:/.test(line.trim()))
    .join("\n");

  // Worker engine selection on iOS — union of:
  //   1. build.zc `//> define: ZAPP_WORKER_ENGINE_*` declarations (the
  //      escape hatch path).
  //   2. zapp.config.ts headless entries' `engine:` field (the
  //      modern path — what hello-world and most apps use).
  // Falls back to bare-jsc (zero binary cost via the JSC system
  // framework; JIT-less on iOS by Apple policy) when neither source
  // names an engine.
  //
  // bare-v8 is intentionally NOT exposed for iOS — V8 needs JIT pages
  // (`MAP_JIT`) which Apple gates behind entitlements not granted to
  // App Store apps. If the user named bare-v8 in either source, we
  // warn and fall back to bare-jsc.
  const userPickedBareJsc   = /^\/\/>.*define:.*ZAPP_WORKER_ENGINE_BARE_JSC/m.test(content);
  const userPickedBareQuick = /^\/\/>.*define:.*ZAPP_WORKER_ENGINE_BARE_QUICKJS/m.test(content);
  const userPickedBareV8    = /^\/\/>.*define:.*ZAPP_WORKER_ENGINE_BARE_V8/m.test(content);
  const userPickedBareHermes = /^\/\/>.*define:.*ZAPP_WORKER_ENGINE_BARE_HERMES/m.test(content);
  const userPickedZjs       = /^\/\/>.*define:.*ZAPP_WORKER_ENGINE_ZJS\b/m.test(content);

  // Walk zapp.config.ts headless entries to pick up engines named
  // there but not declared in build.zc. Same engine set the
  // engine-overlay generator looks at — they need to stay in sync
  // so the iOS build sees the same engine list as the macOS build.
  const configEngines = new Set<string>();
  for (const value of Object.values(config?.headless ?? {})) {
    if (typeof value === "object" && value && "engine" in value && value.engine) {
      configEngines.add(value.engine);
    }
  }
  const configHasBareJsc    = configEngines.has("bare-jsc");
  const configHasBareQuick  = configEngines.has("bare-quickjs");
  const configHasBareV8     = configEngines.has("bare-v8");
  const configHasBareHermes = configEngines.has("bare-hermes");
  const configHasZjs        = configEngines.has("zjs");

  // V8 on iOS is a dead end: full V8 needs JIT pages (`mmap(PROT_EXEC)`)
  // which Apple gates behind a JIT entitlement not granted to App
  // Store apps. The fallback (jitless V8) would run as a ~30 MB
  // interpreter — perf is on par with bare-quickjs at ~1.5 MB.
  // Surface this explicitly so users don't think they're getting V8
  // speed on their iOS build.
  if (userPickedBareV8 || configHasBareV8) {
    process.stdout.write(
      "[zapp] note: bare-v8 isn't useful on iOS (no JIT entitlement for App Store apps).\n" +
      "       Falling back to bare-jsc for this build.\n" +
      "       Use 'bare-quickjs' explicitly if you want cross-platform interpreter parity.\n"
    );
  }

  const engineDefines: string[] = [];
  if (userPickedBareJsc    || configHasBareJsc)    engineDefines.push("ZAPP_WORKER_ENGINE_BARE_JSC");
  if (userPickedBareQuick  || configHasBareQuick)  engineDefines.push("ZAPP_WORKER_ENGINE_BARE_QUICKJS");
  if (userPickedBareHermes || configHasBareHermes) engineDefines.push("ZAPP_WORKER_ENGINE_BARE_HERMES");
  if (userPickedZjs        || configHasZjs)        engineDefines.push("ZAPP_WORKER_ENGINE_ZJS");
  if (engineDefines.length === 0) engineDefines.push("ZAPP_WORKER_ENGINE_BARE_JSC");

  const iosOverlay = `
// AUTO-GENERATED for iOS builds. Strips macos:-prefixed directives
// from the user's build.zc (which zc applies based on host platform
// rather than build target) and re-emits the iOS-appropriate set.
//> define: apple
${engineDefines.map(d => `//> define: ${d}`).join("\n")}
`;

  // Write next to the user's build.zc so relative imports
  // (`import "app.zc"`) still resolve. Using an underscore prefix
  // makes it visually distinct from hand-authored sources; safe to
  // gitignore via `zapp/_zapp_build_ios.zc`.
  const iosBuildFile = path.join(path.dirname(originalBuildFile), "_zapp_build_ios.zc");
  await Bun.write(iosBuildFile, iosOverlay + filtered);
  return iosBuildFile;
}

// Generate `.zapp/zapp_engine_overlay.zc` — a build-time overlay that adds
// `//> define: ZAPP_WORKER_ENGINE_*` directives for engines a user reached
// for in `zapp.config.ts` headless map but didn't manually opt into via
// `zapp/build.zc`. Lets users say `engine: "bare-quickjs"` in config and
// have the engine "just appear" in the build — the CLI builds engines you
// reference; you don't have to learn build directives to use a worker.
//
// Returns the overlay file path, or null if no overlay is needed (every
// engine the project references is already declared in build.zc).
// Idempotent flag for the "engine declared in build.zc is deprecated"
// nudge — module-scoped so dev mode's repeated rebuilds don't spam
// the same warning on every save.
let _engineBuildZcWarned = false;

export async function generateEngineOverlay(opts: {
  root: string;
  target: BuildTarget;
  config: ResolvedConfig;
}): Promise<string | null> {
  const { root, target, config } = opts;

  // 1. Read what's already in build.zc.
  const buildFile = path.join(root, "zapp", "build.zc");
  let buildContent = "";
  try { buildContent = await Bun.file(buildFile).text(); } catch {}

  const declared = (m: string) => new RegExp(`^//>.*define:.*${m}\\b`, "m").test(buildContent);
  const have = {
    "bare-jsc":    declared("ZAPP_WORKER_ENGINE_BARE_JSC"),
    "bare-v8":     declared("ZAPP_WORKER_ENGINE_BARE_V8"),
    "bare-quickjs":declared("ZAPP_WORKER_ENGINE_BARE_QUICKJS"),
    "bare-mqjs":   declared("ZAPP_WORKER_ENGINE_BARE_MQJS"),
    "bare-hermes": declared("ZAPP_WORKER_ENGINE_BARE_HERMES"),
    zjs:           declared("ZAPP_WORKER_ENGINE_ZJS"),
  };

  // Deprecation nudge — engine selection now lives in zapp.config.ts
  // (the CLI synthesizes the matching `ZAPP_WORKER_ENGINE_*` define).
  // The build.zc `//>` form keeps working as an escape hatch for now,
  // but spelling the engine in two places lets the sources of truth
  // drift silently. Warn once per offending define so existing apps
  // know what to migrate without spamming on every rebuild.
  const declaredInBuildZc = (Object.entries(have) as [string, boolean][])
    .filter(([, v]) => v)
    .map(([k]) => k);
  if (declaredInBuildZc.length > 0 && !_engineBuildZcWarned) {
    _engineBuildZcWarned = true;
    process.stderr.write(
      `[zapp] zapp/build.zc declares engine define(s) for ${declaredInBuildZc.join(", ")} ` +
      `via \`//> define: ZAPP_WORKER_ENGINE_*\`. Engine selection has moved to ` +
      `zapp.config.ts — set \`engine: "..."\` on the relevant headless entry (and ` +
      `the CLI emits the matching define). The build.zc form still works but is ` +
      `deprecated; expect removal in a future alpha.\n`
    );
  }

  // 2. Walk headless config — pick up any `engine:` field.
  const wanted = new Set<string>();
  for (const value of Object.values(config.headless ?? {})) {
    if (typeof value === "object" && value && "engine" in value && value.engine) {
      wanted.add(value.engine);
    }
  }

  // 3. If the project references workers but no engine is named anywhere
  //    (neither a build.zc `//>` directive nor a per-worker `engine:`
  //    field in `zapp.config.ts`), pick a sensible per-platform default.
  //    The matrix lives in cli/src/native.ts:defaultBareEngine — bare-jsc
  //    on Apple (free, JIT with entitlement), bare-v8 elsewhere.
  //
  //    Checking `wanted.size === 0` here (not just `!anyDeclared`) is
  //    load-bearing once apps stop declaring engines in build.zc and
  //    rely purely on `zapp.config.ts`. Otherwise a config-pinned worker
  //    (e.g. `engine: "zjs"`) would also pull in the default bare-* —
  //    duplicate engine in the binary, wrong worker engine picked at
  //    runtime if the resolver downgrade chain crosses them.
  const anyDeclared = Object.values(have).some(Boolean);
  const hasWorkers = (config.headless && Object.keys(config.headless).length > 0)
    || wanted.size > 0;
  if (!anyDeclared && wanted.size === 0 && hasWorkers) {
    // Defer the import — keep this file's deps narrow.
    const { defaultBareEngine } = await import("./native");
    const engine = defaultBareEngine(target);
    wanted.add("bare-" + engine);
  }

  // 4. Compute the missing set (wanted - already-declared).
  const missing: string[] = [];
  for (const w of wanted) {
    if (!(w in have)) continue; // unknown engine string — config validation should've caught it
    if (!have[w as keyof typeof have]) {
      const def = w === "bare-jsc"      ? "ZAPP_WORKER_ENGINE_BARE_JSC"
                : w === "bare-v8"       ? "ZAPP_WORKER_ENGINE_BARE_V8"
                : w === "bare-quickjs"  ? "ZAPP_WORKER_ENGINE_BARE_QUICKJS"
                : w === "bare-mqjs"     ? "ZAPP_WORKER_ENGINE_BARE_MQJS"
                : w === "bare-hermes"   ? "ZAPP_WORKER_ENGINE_BARE_HERMES"
                : w === "zjs"           ? "ZAPP_WORKER_ENGINE_ZJS"
                : null;
      if (def) missing.push(def);
    }
  }

  if (missing.length === 0) return null;

  // Apple-target engines are macOS- AND iOS-relevant; we leave the
  // platform prefix off so zc applies to whichever host. (`generateIOSBuildFile`
  // strips macos: directives, so a non-prefixed define carries through to iOS.)
  const body = `// AUTO-GENERATED engine overlay. Adds defines for engines reached
// for in zapp.config.ts but not declared in zapp/build.zc.
${missing.map(d => `//> define: ${d}`).join("\n")}
`;

  const zappDir = path.join(root, ".zapp");
  await mkdir(zappDir, { recursive: true });
  const overlayPath = path.join(zappDir, "zapp_engine_overlay.zc");
  await Bun.write(overlayPath, body);
  return overlayPath;
}

// Generate .zapp/zapp_platform.zc with .m file cflags. The optional
// `engineOverlayFile` lets the platform scan also see engine defines
// the CLI auto-generated from zapp.config.ts (parallels how
// generateEngineOverlay produces them).
export async function generatePlatformConfig(
  root: string,
  target: BuildTarget = detectTarget(),
  buildFile?: string,
  engineOverlayFile?: string,
  config?: ResolvedConfig,
): Promise<string> {
  const zappDir = path.join(root, ".zapp");
  await mkdir(zappDir, { recursive: true });

  const nativeDir = resolveNativeDir();
  const sources = getPlatformSources(nativeDir, target);

  // Append user-authored ObjC/C sources from the project's zapp/ tree.
  // This lets apps ship a service implementation in a .m (or .c on
  // Windows) file without modifying the framework. Scans recursively.
  const userSources = await getUserProjectSources(root, target);
  if (userSources.length > 0) {
    sources.push(...userSources);
    const relPaths = userSources.map(s => path.relative(root, s));
    process.stdout.write(`[zapp] user sources: ${relPaths.join(", ")}\n`);
  }

  // Check enabled worker engines from user's build.zc directives AND
  // from the CLI-generated engine overlay (when present). Concatenating
  // the two sources lets users name engines in zapp.config.ts without
  // also having to add `//> define:` directives by hand.
  const bareEngines: ("v8" | "jsc" | "quickjs" | "mqjs" | "hermes")[] = [];
  const userBuild = buildFile ?? path.join(root, "zapp", "build.zc");
  let buildContent = "";
  try { buildContent += await Bun.file(userBuild).text() + "\n"; } catch {}
  if (engineOverlayFile) {
    try { buildContent += await Bun.file(engineOverlayFile).text(); } catch {}
  }
  const hasZjs = /^\/\/>.*define:.*ZAPP_WORKER_ENGINE_ZJS\b/m.test(buildContent);
  if (/^\/\/>.*define:.*ZAPP_WORKER_ENGINE_BARE_V8/m.test(buildContent)) bareEngines.push("v8");
  if (/^\/\/>.*define:.*ZAPP_WORKER_ENGINE_BARE_JSC/m.test(buildContent)) bareEngines.push("jsc");
  if (/^\/\/>.*define:.*ZAPP_WORKER_ENGINE_BARE_QUICKJS/m.test(buildContent)) bareEngines.push("quickjs");
  if (/^\/\/>.*define:.*ZAPP_WORKER_ENGINE_BARE_MQJS/m.test(buildContent)) bareEngines.push("mqjs");
  if (/^\/\/>.*define:.*ZAPP_WORKER_ENGINE_BARE_HERMES/m.test(buildContent)) bareEngines.push("hermes");
  if (bareEngines.length > 0) {
    // Single bare.c source handles all enabled engines via #ifdef on
    // the ZAPP_WORKER_ENGINE_BARE_* defines. The libs differ per
    // engine but the dispatcher code is the same.
    const bareC = path.join(nativeDir, "worker", "engines", "bare.c");
    if (existsSync(bareC)) sources.push(bareC);
  }
  if (hasZjs) {
    const zjsC = path.join(nativeDir, "worker", "engines", "zjs.c");
    if (existsSync(zjsC)) sources.push(zjsC);
  }

  let content = "// AUTO-GENERATED by zapp CLI. Do not edit.\n// Platform-specific compilation sources.\n\n";

  // Emit paths relative to the project root when that's shorter than the
  // absolute form. zc has a fixed-size buffer for accumulated build
  // directives; long absolute paths (especially for projects installing
  // the CLI under node_modules/@zappdev/cli/) can overflow it, silently
  // dropping trailing directives. Since zc invokes clang with cwd = project
  // root, relative paths resolve identically. Picking the shorter form
  // per-path keeps vendor paths in ~/.zapp/vendor from blowing up as
  // "../../../../..".
  const shortPath = (abs: string): string => {
    const rel = path.relative(root, abs);
    return rel.length < abs.length ? rel : abs;
  };

  // Per-target bucket key for `resolvePlatformValue` (collapses both
  // iOS subtargets to "ios" — same source set + same extras apply).
  const platformKey: "macos" | "ios" | "windows" =
    target === "macos"   ? "macos"
    : isIOSTarget(target) ? "ios"
    : "windows";
  const userNativeSources = resolvePlatformValue(config?.nativeSources,  platformKey);
  const userExtraFrameworks = resolvePlatformValue(config?.extraFrameworks, platformKey);
  const userExtraLinkFlags  = resolvePlatformValue(config?.extraLinkFlags,  platformKey);
  // Resolve user source paths relative to project root.
  const resolvedUserSources = userNativeSources.map(s => path.resolve(root, s));

  if (target === "macos" && sources.length > 0) {
    // ObjC ARC for the framework's own .m files. Bundle `-fobjc-arc`
    // onto the same `//> macos: cflags:` line as the sources so zc
    // applies it directly to those compile units. Splitting it onto
    // its own directive intermittently lost the flag on bench-shaped
    // builds (window.m's `__weak NSWindow*` then failed with
    // "cannot create __weak reference in file using manual reference
    // counting").
    const macSources = [...sources, ...resolvedUserSources];
    content += `//> macos: cflags: -fobjc-arc ${macSources.map(shortPath).join(" ")}\n`;
    // Framework-internal system framework set — the boilerplate that
    // every Zapp macOS app needs, regardless of what the app itself
    // links. Generating these here means the user's hand-written
    // `zapp/build.zc` stays free of platform plumbing it shouldn't
    // know about. Apps that need additional frameworks declare them
    // via `extraFrameworks` in zapp.config.ts.
    content += `//> macos: framework: Cocoa\n`;
    content += `//> macos: framework: WebKit\n`;
    content += `//> macos: framework: CoreFoundation\n`;
    content += `//> macos: framework: JavaScriptCore\n`;
    content += `//> macos: framework: Security\n`;
    content += `//> macos: framework: UserNotifications\n`;
    // Carbon — RegisterEventHotKey + friends for shortcuts.m.
    content += `//> macos: framework: Carbon\n`;
    // libcompression — embedded-asset brotli decode path.
    content += `//> macos: link: -lcompression\n`;
    // App-declared extras from zapp.config.ts.
    for (const fw of userExtraFrameworks) content += `//> macos: framework: ${fw}\n`;
    if (userExtraLinkFlags.length > 0) {
      content += `//> macos: link: ${userExtraLinkFlags.join(" ")}\n`;
    }
  }
  if (isIOSTarget(target) && sources.length > 0) {
    // Pick the right SDK + arch for the target. Simulator on Apple
    // Silicon Macs is arm64 (uses iphonesimulator SDK with simulator
    // version-min); device is arm64 too but uses iphoneos SDK and the
    // production version-min. Both flow through clang via cflags
    // pass-through; zc itself doesn't need iOS-specific knowledge.
    const sdk = target === "ios-simulator" ? "iphonesimulator" : "iphoneos";
    const versionMinFlag = target === "ios-simulator"
      ? "-mios-simulator-version-min=15.0"
      : "-miphoneos-version-min=15.0";
    // resolveSdkPath caches the xcrun result; called once per build.
    const sdkPath = await resolveSDKPath(sdk);
    const iosCflags = [
      "-arch", "arm64",
      "-isysroot", sdkPath,
      versionMinFlag,
      // ObjC ARC is on for our .m sources; matches the macOS path.
      "-fobjc-arc",
    ].join(" ");
    const iosSources = [...sources, ...resolvedUserSources];
    content += `//> cflags: ${iosCflags} ${iosSources.map(shortPath).join(" ")}\n`;
    content += `//> link: -arch arm64 -isysroot ${sdkPath} ${versionMinFlag}\n`;
    // iOS frameworks: UIKit replaces Cocoa; WebKit + JavaScriptCore
    // are the same as macOS. Foundation is implicit but listing it for
    // clarity. No Carbon — RegisterEventHotKey / shortcuts.m are
    // macOS-only and the iOS shortcuts.m is a no-op stub.
    content += `//> framework: UIKit\n`;
    content += `//> framework: Foundation\n`;
    content += `//> framework: WebKit\n`;
    content += `//> framework: JavaScriptCore\n`;
    // UniformTypeIdentifiers — used by ios/dialog.m for UIDocumentPicker
    // file-type filtering (UTType). iOS 14+ system framework.
    content += `//> framework: UniformTypeIdentifiers\n`;
    // UserNotifications — used by ios/notification.m. Same framework as
    // macOS (UNUserNotificationCenter API is cross-Apple-platform).
    content += `//> framework: UserNotifications\n`;
    // libcompression — used by jsc.m for embedded-asset brotli decode.
    // Available on iOS as a system library; just needs the link flag.
    content += `//> link: -lcompression\n`;
    // App-declared extras from zapp.config.ts.
    for (const fw of userExtraFrameworks) content += `//> framework: ${fw}\n`;
    if (userExtraLinkFlags.length > 0) {
      content += `//> link: ${userExtraLinkFlags.join(" ")}\n`;
    }
  }
  // Worker-engine link plumbing — accumulate all -L search paths and
  // -l<name> flags into a single `//> link:` directive emitted at the end.
  const allLinkSearchDirs: string[] = [];
  const allLinkLibs: string[] = [];

  // Bare runtime — link each enabled engine. Use zc's dedicated
  // `//> include:` (for -I) and `//> lib:` (for -L) directives rather
  // than packing -I/-L into `cflags:` / `link:`. Per the docs (Zen-C
  // tour 12.5 Build Directives), these have purpose-specific
  // accumulation behavior; bundling search paths into a generic
  // link: directive doesn't reliably extend the previous one.
  if (bareEngines.length > 0) {
    const { resolveBareDir } = await import("./paths");
    const { bareBuildDirName } = await import("./native");
    const bareDir = await resolveBareDir();
    const bareInclude = path.join(bareDir, "include");
    if (existsSync(path.join(bareInclude, "bare.h"))) {
      content += `//> cflags: -I${shortPath(bareInclude)}\n`;

      for (const engine of bareEngines) {
        const buildSubdir = bareBuildDirName(target, engine);
        const bareBuild = path.join(bareDir, buildSubdir);
        // js.h lives in the libjs abstraction layer (always pulled in
        // by Bare regardless of which engine backs it).
        const libjsInclude = path.join(bareBuild, "_deps",
            "github+holepunchto+libjs-src", "include");
        if (existsSync(libjsInclude)) {
          content += `//> cflags: -I${shortPath(libjsInclude)}\n`;
        }
        const engineSrcMap: Record<string, string> = {
          v8: "github+holepunchto+libjs-src",
          jsc: "github+holepunchto+libjsc-src",
          quickjs: "github+holepunchto+libqjs-src",
          mqjs: "github+holepunchto+libmqjs-src",
          hermes: "github+popaprozac+libhermes-src",
        };
        const engineSrc = path.join(bareBuild, "_deps", engineSrcMap[engine], "include");
        if (existsSync(engineSrc) && engine !== "v8") {
          content += `//> cflags: -I${shortPath(engineSrc)}\n`;
        }
        const libuvInclude = path.join(bareBuild, "_deps",
            "github+libuv+libuv-src", "include");
        if (existsSync(libuvInclude)) {
          content += `//> cflags: -I${shortPath(libuvInclude)}\n`;
        }
        const libutfInclude = path.join(bareBuild, "_deps",
            "github+holepunchto+libutf-src", "include");
        if (existsSync(libutfInclude)) {
          content += `//> cflags: -I${shortPath(libutfInclude)}\n`;
        }
        const libBare = path.join(bareBuild, "libbare.a");
        if (existsSync(libBare)) {
          // V8 uses BARE_PREBUILDS=ON which places libjs.a (and libv8.a,
          // libc++.a) under `darwin-arm64/` rather than the usual
          // `_deps/<repo>-build` tree the other engines use.
          let engineBuild: string;
          if (engine === "v8") {
            engineBuild = path.join(bareBuild, "darwin-arm64");
          } else {
            const engineBuildMap: Record<string, string> = {
              jsc: "github+holepunchto+libjsc-build",
              quickjs: "github+holepunchto+libqjs-build",
              mqjs: "github+holepunchto+libmqjs-build",
              hermes: "github+popaprozac+libhermes-build",
            };
            engineBuild = path.join(bareBuild, "_deps", engineBuildMap[engine]);
          }
          const libuvBuild = path.join(bareBuild, "_deps", "github+libuv+libuv-build");
          const libutfBuild = path.join(bareBuild, "_deps", "github+holepunchto+libutf-build");
          // We pass static .a files as positional arguments rather
          // than `-L<dir> -l<name>` for libuv specifically. Reason:
          // homebrew installs `libuv.dylib` in `/opt/homebrew/lib/`,
          // which is on most devs' default link search path
          // (LIBRARY_PATH or implicit). With bare compiled in, `-luv`
          // falls through to homebrew's dylib — produces a binary with
          // an unsatisfiable @rpath/libuv.1.dylib reference at launch.
          // Passing the .a file directly forces static linking and
          // makes the build platform-installed-dylib-proof.
          //
          // For libutf and the engine-specific binding (libjs.a) we
          // keep the -L+-l form because there's no system collision —
          // those libs only exist in our build dir.
          const libuvA = path.join(libuvBuild, "libuv.a");
          // For V8 we skip adding engineBuild to -L; otherwise `-lc++`
          // resolves to V8's bundled libc++.a (`__Cr` namespace)
          // before falling through to Apple's stock libc++ (`__1`
          // namespace), and BoringSSL needs the latter. We pass
          // libv8.a + libc++.a positionally below instead.
          allLinkSearchDirs.push(shortPath(bareBuild));
          if (engine !== "v8") allLinkSearchDirs.push(shortPath(engineBuild));
          allLinkSearchDirs.push(shortPath(libutfBuild));
          allLinkLibs.push("-lbare");
          if (engine !== "v8") allLinkLibs.push("-ljs");
          allLinkLibs.push("-lutf");
          if (engine === "v8") {
            const libjsA = path.join(engineBuild, "libjs.a");
            if (existsSync(libjsA)) {
              const flag = shortPath(libjsA);
              if (!allLinkLibs.includes(flag)) allLinkLibs.push(flag);
            }
          }
          if (existsSync(libuvA)) {
            // Avoid duplicates if multiple bare engines compile in.
            const libuvFlag = shortPath(libuvA);
            if (!allLinkLibs.includes(libuvFlag)) allLinkLibs.push(libuvFlag);
          }
          // V8 needs the engine itself + libc++ as separate libs (the
          // libjsc binding is header-only against the system framework
          // so doesn't need this; QJS and mQJS link the engine via
          // their respective libjs binding).
          //
          // CRUCIAL detail when BoringSSL is also on the link line:
          // V8's prebuilt libc++.a uses Holepunch's custom inline
          // namespace `__Cr` (the build uses LIBCXX_ABI_NAMESPACE to
          // avoid clashing with the system libc++), while Apple's
          // stock libc++ uses `__1`. They expose completely different
          // mangled symbols. BoringSSL was compiled against stock
          // Apple libc++, so it needs `__1` versions of std::__sort
          // etc., which V8's bundled libc++.a CANNOT provide.
          //
          // We solve this by:
          //   1. Passing V8's libc++.a as an absolute positional
          //      argument — gives `__Cr` symbols for V8 itself.
          //   2. NOT also pushing `-lc++` here (the BoringSSL block
          //      below pushes it, which resolves to Apple's system
          //      libc++ providing the `__1` symbols).
          //
          // Without (1), V8 can't find its `__Cr` symbols. Without
          // (2), BoringSSL can't find its `__1` symbols. Both libs
          // coexist on the link line because the symbols are in
          // separate namespaces, so no duplicate-symbol conflict.
          if (engine === "v8") {
            const v8A = path.join(engineBuild, "libv8.a");
            if (existsSync(v8A)) {
              const flag = shortPath(v8A);
              if (!allLinkLibs.includes(flag)) allLinkLibs.push(flag);
            }
            const v8Cxx = path.join(engineBuild, "libc++.a");
            if (existsSync(v8Cxx)) {
              const flag = shortPath(v8Cxx);
              if (!allLinkLibs.includes(flag)) allLinkLibs.push(flag);
            }
          }
          // QuickJS and mQJS produce a separate libqjs.a / libmqjs.a
          // alongside libjs.a; both need linking.
          if (engine === "quickjs") {
            allLinkSearchDirs.push(shortPath(
              path.join(bareBuild, "_deps", "github+quickjs-ng+quickjs-build")
            ));
            allLinkLibs.push("-lqjs", "-lc++");
          }
          if (engine === "mqjs") {
            allLinkLibs.push("-lmqjs");
          }
          if (engine === "hermes") {
            // libhermes pins BUILD_SHARED_LIBS=OFF (see
            // libhermes/CMakeLists.txt), so Hermes produces static
            // archives. On Apple, HERMES_BUILD_APPLE_FRAMEWORK
            // defaults ON and Hermes wraps libhermesvm.a as a
            // framework bundle whose binary IS a static archive.
            // Apple's ld can link this via `-framework hermesvm`.
            const hermesBuildRoot = path.join(bareBuild, "_deps", "github+facebook+hermes-build");
            const hermesVmFwkCandidates = [
              path.join(hermesBuildRoot, "API", "hermes", "hermesvm.framework"),
              path.join(bareBuild, "lib", "hermesvm.framework"),
            ];
            const hermesVmFwk = hermesVmFwkCandidates.find(p => existsSync(p));
            const hermesVmLibA = path.join(hermesBuildRoot, "API", "hermes", "libhermesvm.a");
            if (hermesVmFwk) {
              allLinkLibs.push("-F" + shortPath(path.dirname(hermesVmFwk)));
              allLinkLibs.push("-framework", "hermesvm");
            } else if (existsSync(hermesVmLibA)) {
              const flag = shortPath(hermesVmLibA);
              if (!allLinkLibs.includes(flag)) allLinkLibs.push(flag);
            }
            // jsi follows BUILD_SHARED_LIBS / HERMES_BUILD_SHARED_JSI
            // — libhermes pins both OFF, so we get libjsi.a.
            const jsiLibA = path.join(hermesBuildRoot, "jsi", "libjsi.a");
            const jsiLibDylib = path.join(hermesBuildRoot, "jsi", "libjsi.dylib");
            if (existsSync(jsiLibA)) {
              const flag = shortPath(jsiLibA);
              if (!allLinkLibs.includes(flag)) allLinkLibs.push(flag);
            } else if (existsSync(jsiLibDylib)) {
              allLinkSearchDirs.push(shortPath(path.dirname(jsiLibDylib)));
              allLinkLibs.push("-ljsi");
            }
            // Hermes' framework binary only contains symbols from
            // API/hermes/*.cpp — not the underlying VM, optimizer,
            // parser, or LLVH support libraries. Those live as
            // ~25 separate static archives under `_deps/.../lib/*`
            // and `_deps/.../external/llvh/lib/*`.
            //
            // cmake's transitive PRIVATE link deps don't propagate
            // when we're linking by hand. Putting all 25 paths on
            // a single `//> link:` directive overflows Zen-C's
            // 8KB `g_link_flags` buffer (the buffer would be fine
            // for 25 short -l<name> entries, but our paths are
            // ~95 chars each → 2.4 KB just for these — and the
            // strncat-based accumulator in append_flag silently
            // truncates the last few paths instead of erroring).
            //
            // Solution: merge them into one combined archive via
            // libtool at build-config time, then link only that.
            // Static archive merge is cheap (just an `ar` table
            // rebuild — no compilation) and the resulting file is
            // dead-stripped by ld at the final link.
            const hermesLibGlobs = [
              path.join(hermesBuildRoot, "lib"),
              path.join(hermesBuildRoot, "external"),
              path.join(hermesBuildRoot, "public", "hermes", "Public"),
            ];
            const walkForA = (dir: string, out: string[]) => {
              if (!existsSync(dir)) return;
              const fs = require("fs") as typeof import("fs");
              for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
                const p = path.join(dir, entry.name);
                if (entry.isDirectory()) walkForA(p, out);
                else if (entry.isFile() && /^lib(hermes|LLVH|dtoa)[A-Za-z0-9]*\.a$/.test(entry.name)) {
                  out.push(p);
                }
              }
            };
            const hermesArchives: string[] = [];
            for (const root of hermesLibGlobs) walkForA(root, hermesArchives);
            if (hermesArchives.length > 0) {
              const combinedPath = path.join(hermesBuildRoot, "libhermes_combined.a");
              const fs = require("fs") as typeof import("fs");
              const newest = Math.max(...hermesArchives.map(p => fs.statSync(p).mtimeMs));
              const stale = !existsSync(combinedPath) || fs.statSync(combinedPath).mtimeMs < newest;
              if (stale) {
                const { execFileSync } = require("child_process") as typeof import("child_process");
                if (existsSync(combinedPath)) fs.unlinkSync(combinedPath);
                execFileSync("libtool", ["-static", "-o", combinedPath, ...hermesArchives], { stdio: "inherit" });
              }
              const flag = shortPath(combinedPath);
              if (!allLinkLibs.includes(flag)) allLinkLibs.push(flag);
            }
            // Hermes is C++ — pulls in std symbols. Uses the stock
            // libc++ namespace `__1`, so system libc++ is correct.
            if (!allLinkLibs.includes("-lc++")) allLinkLibs.push("-lc++");
          }
          // Bare's stdlib modules (bare-buffer, bare-os, bare-timers,
          // bare-buffer, etc.) live as separate binding.c.o objects
          // outside libbare.a. Each registers itself with the runtime
          // via a static-init constructor, which means we need
          // -force_load so the linker keeps the .o even though no
          // symbol from it is referenced from our code. Without this
          // bare.js fails on `require('bare-buffer')` and the runtime
          // crashes during bare_setup. The combined archive is built
          // in cli/src/native.ts after the bare cmake build.
          const libBareModules = path.join(bareBuild, "libbare_modules.a");
          if (existsSync(libBareModules)) {
            allLinkLibs.push(`-Wl,-force_load,${shortPath(libBareModules)}`);
          }

          // Several bare-* bindings have heavyweight transitive
          // C deps that bare's cmake fetches but doesn't bundle into
          // libbare.a. When the corresponding binding.c.o is in
          // libbare_modules.a (because we now build bare_bin in
          // ensureBareBuilt), we ALSO need to put those deps on the
          // link line.
          //
          //   bare-tls / bare-crypto → BoringSSL (libssl + libcrypto
          //                            + libdecrepit). Symbols like
          //                            BIO_clear_retry_flags.
          //   bare-dns               → c-ares (libcares). Symbols
          //                            like ares_destroy.
          //   bare-zlib              → zlib (libz). Symbols like
          //                            deflateInit_ / inflate.
          //
          // The .a files live in different roots depending on which
          // cmake project built them:
          //   - macOS: vendor/bare's main build dir (bare_bin's
          //     transitive fetches).
          //   - iOS: the user-modules overlay (bare_bin isn't built
          //     on iOS, so the overlay re-fetches them via its own
          //     link_bare_module calls for bare-tcp/tls/dns/etc.).
          //
          // Probe both. We don't gate on which modules are present —
          // unused libs cost nothing because the linker dead-strips
          // unreferenced sections.
          const depRoots = [
            path.join(bareBuild, "_deps"),
            path.join(bareBuild, "zapp-user-modules", "build", "_deps"),
          ];
          for (const depRoot of depRoots) {
            const boringsslDir = path.join(depRoot, "github+google+boringssl-build");
            if (existsSync(path.join(boringsslDir, "libssl.a"))) {
              const dir = shortPath(boringsslDir);
              if (!allLinkSearchDirs.includes(dir)) allLinkSearchDirs.push(dir);
              if (!allLinkLibs.includes("-lssl")) {
                allLinkLibs.push("-lssl", "-lcrypto", "-ldecrepit");
              }
              // BoringSSL is C++ — pulls in std::__sort, std::terminate,
              // etc. The final binary is linked with clang (C), so we
              // need libc++ explicitly, and CRUCIALLY it has to come
              // AFTER the BoringSSL libs. Apple's ld doesn't re-scan
              // static archives once it passes them, so a `-lc++`
              // pushed earlier (e.g. by the V8 engine branch at
              // engine === "v8") doesn't satisfy libssl's references.
              //
              // Pull any existing `-lc++` out of the list first, then
              // re-push it here. Idempotent in the dedup sense, but
              // order-sensitive — which is the whole point.
              const cppIdx = allLinkLibs.indexOf("-lc++");
              if (cppIdx >= 0) allLinkLibs.splice(cppIdx, 1);
              allLinkLibs.push("-lc++");
            }
            const caresLib = path.join(depRoot, "github+c-ares+c-ares-build", "src", "lib", "libcares.a");
            if (existsSync(caresLib)) {
              const flag = shortPath(caresLib);
              if (!allLinkLibs.includes(flag)) allLinkLibs.push(flag);
            }
            const zlibLib = path.join(depRoot, "github+madler+zlib-build", "libz.a");
            if (existsSync(zlibLib)) {
              const flag = shortPath(zlibLib);
              if (!allLinkLibs.includes(flag)) allLinkLibs.push(flag);
            }
          }
        }
      }
    }
  }

  // Flush all accumulated -L paths + -l flags as a single //> link:
  // directive. Single-line is the form zc handles cleanly — splitting
  // search paths into //> lib: directives or libs into multiple //>
  // link: lines caused only the first to be honored in tests on
  // zc v0.4.3.
  if (allLinkLibs.length > 0 || allLinkSearchDirs.length > 0) {
    const allFlags = [
      ...allLinkSearchDirs.map(d => `-L${d}`),
      ...allLinkLibs,
    ];
    content += `//> link: ${allFlags.join(" ")}\n`;
  }

  // zjs engine — independent of bare. Auto-builds the right libzjs
  // artifact if missing (one `make -C vendor/zjs [target]` invocation;
  // zjs's own Makefile handles the rest), then emits the include + link
  // directives. macOS + iOS Simulator today — Linux / Windows plumbing
  // follows once zjs ships uv-free platform shims for those targets or
  // we vendor libuv ourselves.
  //
  // iOS device (`ios-device`) is intentionally NOT covered yet — the
  // device toolchain build path is a separate follow-up (the kqueue-
  // apple branch scopes to Simulator only).
  if (hasZjs && (target === "macos" || target === "ios-simulator")) {
    const { resolveVendorDir } = await import("./paths");
    const vendorDir = resolveVendorDir();
    const zjsDir = path.join(vendorDir, "zjs");
    const zjsInclude = path.join(zjsDir, "include");

    // Branch make invocation + output artifact by target.
    //
    // macOS: link the dylib, not the .a. Both the framework and
    //   libzjs.a embed zenc's stdlib (Vec / String / Option / Arena / …)
    //   — linking the .a fails with hundreds of duplicate-symbol errors
    //   on those shared internals. The dylib resolves symbols per-binary,
    //   so the framework sees only zjs's exported zjs_* surface and its
    //   own copy of the stdlib stays unconflicted.
    //
    //   Long-term fix lives upstream in zjs: ship an embed-friendly .a
    //   with internal symbols stripped (ld -r + -unexported_symbols_list,
    //   or build a relocatable .o with `-hidden`). Until then the dylib
    //   is the right pragmatic choice — runtime dylib dependency is
    //   acceptable since libzjs.dylib lives next to the binary in dev
    //   and bundles into the .app in prod.
    //
    // iOS Simulator: same duplicate-symbol risk as macOS would have
    //   with the .a, but dylibs aren't viable on iOS (Apple's toolchain
    //   expects third-party native libs to link statically into the
    //   app binary). We work around it by post-processing libzjs.a
    //   into an "embed-friendly" archive (libzjs_embed.a) where every
    //   non-`_zjs_*` symbol is `ld -r`'d into a single relocatable
    //   .o with private-extern visibility (`-exported_symbols_list`
    //   restricted to `_zjs_*`). The framework only ever calls into
    //   `zjs_*`, so hiding the rest is safe — and the framework's own
    //   copy of zenc's stdlib (Arena / Vec / String / …) wins the link.
    //   See the build step below the install_name section.
    let zjsLib: string;
    let makeCmd: string[];
    let buildLabel: string;
    if (target === "ios-simulator") {
      zjsLib = path.join(zjsDir, "build", "ios", "simulator-arm64", "libzjs.a");
      makeCmd = ["make", "-C", zjsDir, "ios-simulator-arm64"];
      buildLabel = "vendor/zjs (iOS Sim arm64; first run; ~30s)";
    } else {
      // target === "macos"
      zjsLib = path.join(zjsDir, "build", "libzjs.dylib");
      makeCmd = ["make", "-C", zjsDir];
      buildLabel = "vendor/zjs (first run; ~30s)";
    }

    if (!existsSync(zjsLib)) {
      process.stdout.write(`[zapp] building ${buildLabel}...\n`);
      const proc = Bun.spawn(makeCmd, {
        stdout: "pipe", stderr: "pipe",
      });
      const exitCode = await proc.exited;
      if (exitCode !== 0 || !existsSync(zjsLib)) {
        const stderr = await new Response(proc.stderr).text();
        throw new Error(
          `[zapp] failed to build vendor/zjs (exit ${exitCode}). ` +
          `Tried: ${makeCmd.join(" ")}. Build vendor/zjs by hand and rerun.\n${stderr}`
        );
      }
    }

    // install_name_tool rewrite is macOS-only — iOS uses a static .a,
    // which has no install_name (it's a dylib-only concept).
    //
    // zjs's Makefile bakes a relative install_name ("build/libzjs.dylib")
    // because the dylib is normally consumed in-tree (its own smoke test
    // run from the project root finds it via @loader_path). For Zapp
    // we're linking from a different cwd, so the runtime loader can't
    // resolve the relative path. Rewrite the install_name to the
    // absolute vendor location once — idempotent, fast, no rebuild.
    if (target === "macos") {
      const otoolD = Bun.spawnSync(["otool", "-D", zjsLib]);
      const installName = new TextDecoder().decode(otoolD.stdout).split("\n")[1]?.trim();
      if (installName && installName !== zjsLib) {
        const fix = Bun.spawnSync(["install_name_tool", "-id", zjsLib, zjsLib]);
        if (fix.exitCode !== 0) {
          throw new Error(
            `[zapp] failed to set absolute install_name on ${zjsLib}: ` +
            new TextDecoder().decode(fix.stderr)
          );
        }
      }
    }

    // Headers: zjs's own. The Apple loop in engines/zjs.c is kqueue +
    // CFRunLoop (Task 2 of the kqueue-apple migration), so libuv is no
    // longer a build- or runtime-time dependency on Apple. Linux /
    // Windows zjs ports will reintroduce libuv (or an equivalent shim)
    // under their own platform branches when they land.
    //
    // Per-target framework + link emission:
    //   macOS: -rpath so the framework binary finds libzjs.dylib at
    //     runtime from the vendor build dir. Production builds will
    //     copy the dylib into the .app bundle's Frameworks dir and use
    //     @loader_path instead — Z5 follow-up. CoreFoundation
    //     (CFRunLoopRunInMode) is already in the unconditional macOS
    //     framework set above. Foundation (NSURLSession in zjs's
    //     http_apple.m + ws_apple.m) is not, so we add it here scoped
    //     to the zjs branch.
    //   iOS: no rpath — static lib links directly into the binary.
    //     Foundation is already in the iOS unconditional framework set
    //     (every iOS .m source imports <Foundation/Foundation.h>);
    //     CoreFoundation is brought in transitively by Foundation on
    //     iOS, so neither needs to be re-emitted here.
    //
    // iOS directives use NO platform prefix (mirrors the iOS branch
    // above). zc filters platform-prefixed directives by HOST
    // platform, not build target — so `//> ios:` on a macOS host
    // would get dropped. Plain `//> cflags:` / `//> link:` bypass
    // the filter and apply unconditionally, which is what we want
    // for an iOS build running on a macOS host.
    if (target === "ios-simulator") {
      // Produce an embed-friendly archive: ld -r merges libzjs.a's
      // objects into a single relocatable .o, then `-exported_symbols_list`
      // restricts globally-visible symbols to `_zjs_*`. Every other
      // symbol (Arena__*, Vec__*, the zenc-stdlib runtime that both
      // Zapp's framework and libzjs.a embed) becomes a private extern,
      // resolved within the merged .o and invisible to the final ld
      // pass. That sidesteps the ~37 duplicate-symbol clashes between
      // libzjs.a's stdlib copy and the framework's stdlib copy.
      //
      // Cached by mtime — re-runs after the first build are no-ops.
      const sdkPath = await resolveSDKPath("iphonesimulator");
      const versionMinFlag = "-mios-simulator-version-min=15.0";
      const iosBuildDir = path.join(zjsDir, "build", "ios", "simulator-arm64");
      const embedLib = path.join(iosBuildDir, "libzjs_embed.a");
      const embedObj = path.join(iosBuildDir, "libzjs_embed.o");
      const symsList = path.join(iosBuildDir, "libzjs_embed.syms");
      const aesGcmObj = path.join(iosBuildDir, "aes_gcm.o");
      const aesGcmSrc = path.join(zjsDir, "src", "third-party", "aes-gcm", "aes_gcm.c");
      const fs = await import("node:fs");
      const srcMtime = fs.statSync(zjsLib).mtimeMs;
      const aesGcmSrcMtime = existsSync(aesGcmSrc) ? fs.statSync(aesGcmSrc).mtimeMs : 0;
      const stale = !existsSync(embedLib)
        || fs.statSync(embedLib).mtimeMs < srcMtime
        || fs.statSync(embedLib).mtimeMs < aesGcmSrcMtime;
      if (stale) {
        process.stdout.write("[zapp] post-processing libzjs.a → libzjs_embed.a (iOS Sim)...\n");

        // Compile aes_gcm.c into an object so we can include it in
        // the ld -r merge (libzjs.a references zjs_pc_aes_gcm_* but
        // doesn't contain them — vendor zjs's iOS Makefile target
        // misses this source. Until that's fixed upstream, build it
        // here so the merged .o is self-contained.)
        if (existsSync(aesGcmSrc)) {
          const cc = Bun.spawnSync([
            "clang",
            "-O3",
            "-arch", "arm64",
            "-isysroot", sdkPath,
            versionMinFlag,
            "-I" + path.join(zjsDir, "src"),
            "-c", aesGcmSrc,
            "-o", aesGcmObj,
          ]);
          if (cc.exitCode !== 0) {
            throw new Error(
              `[zapp] failed to compile aes_gcm.c for iOS Sim: ` +
              new TextDecoder().decode(cc.stderr)
            );
          }
        }

        // The exported-symbols list is a single-pattern file matching
        // every `_zjs_*` symbol. `*` is the glob meta in ld's
        // -exported_symbols_list grammar.
        await Bun.write(symsList, "_zjs_*\n");
        const ldArgs = [
          "-r",
          "-arch", "arm64",
          "-platform_version", "ios-simulator", "15.0", "15.0",
          "-syslibroot", sdkPath,
          "-exported_symbols_list", symsList,
          // Force-load every .o in the .a — ld -r otherwise skips
          // unreferenced objects, which would lose half of libzjs.
          "-force_load", zjsLib,
          ...(existsSync(aesGcmObj) ? [aesGcmObj] : []),
          "-o", embedObj,
        ];
        const ld = Bun.spawnSync(["ld", ...ldArgs]);
        if (ld.exitCode !== 0) {
          throw new Error(
            `[zapp] failed to build libzjs_embed.o: ` +
            new TextDecoder().decode(ld.stderr)
          );
        }
        if (existsSync(embedLib)) fs.unlinkSync(embedLib);
        const ar = Bun.spawnSync(["ar", "-rcs", embedLib, embedObj]);
        if (ar.exitCode !== 0) {
          throw new Error(
            `[zapp] failed to repack libzjs_embed.a: ` +
            new TextDecoder().decode(ar.stderr)
          );
        }
      }
      content += `//> cflags: -I${shortPath(zjsInclude)}\n`;
      // Security.framework — `SecRandomCopyBytes` (used by zjs's
      // crypto.subtle key-generation path) lives there. Already in
      // the macOS unconditional framework set above; iOS's
      // unconditional set doesn't include it, so we add it here
      // scoped to the zjs branch.
      content += `//> framework: Security\n`;
      // aes_gcm.c is folded into the embed .o above (vendor zjs's
      // iOS Makefile target misses it — see the embed step). No
      // separate cflags entry needed here.
      content += `//> link: ${shortPath(embedLib)}\n`;
    } else {
      // target === "macos"
      const zjsBuildDir = path.dirname(zjsLib);
      content += `//> macos: cflags: -I${shortPath(zjsInclude)}\n`;
      content += `//> macos: framework: Foundation\n`;
      content += `//> macos: link: ${shortPath(zjsLib)} -Wl,-rpath,${zjsBuildDir}\n`;
    }
  }

  if (process.platform === "win32" && sources.length > 0) {
    // WebView2 SDK include path (self-contained loader — no WebView2Loader.dll needed)
    const vendorDir = resolveVendorDir();
    const webview2Dir = path.join(vendorDir, "webview2");
    const webview2Include = path.join(webview2Dir, "include");
    // -DUNICODE / -D_UNICODE / -DCINTERFACE / -DCOBJMACROS are
    // boilerplate every Win32 + COM/WebView2 app needs — emit here
    // so user `build.zc` doesn't have to know.
    const winSources = [...sources, ...resolvedUserSources];
    content += `//> windows: cflags: -DUNICODE -D_UNICODE -DCINTERFACE -DCOBJMACROS ${winSources.map(shortPath).join(" ")} -I${shortPath(webview2Include)}\n`;
    // Standard Win32 + WebView2 link set — every app needs these,
    // additional libs go in `extraLinkFlags.windows` in zapp.config.ts.
    content += `//> windows: link: -lole32 -lshell32 -luuid -luser32 -lgdi32 -lcomctl32 -lcomdlg32 -lshlwapi\n`;
    content += `//> windows: link: -lwinhttp -lbcrypt -ladvapi32 -lrpcrt4 -lcrypt32 -lversion\n`;
    // App-declared extras from zapp.config.ts. `extraFrameworks` is
    // a no-op here (Apple-only concept); use `extraLinkFlags.windows`
    // for `-l<name>` and similar.
    if (userExtraLinkFlags.length > 0) {
      content += `//> windows: link: ${userExtraLinkFlags.join(" ")}\n`;
    }
  }

  const outPath = path.join(zappDir, "zapp_platform.zc");
  await Bun.write(outPath, content);
  return outPath;
}
