/**
 * Downlevel the embedded `bare.js` bundle for Hermes compatibility.
 *
 * Bare's CMakeLists generates `vendor/bare/src/bare.js.h` — a C
 * header containing the bundled `bare.js` source as a `unsigned
 * char[]` byte array. `bare.c` includes this header and feeds the
 * bytes to `js_run_script` (or its equivalent) during runtime
 * setup. The bundle is produced by `node bundle.js` (cmake-bare-
 * bundle) which calls `bare-pack` + `bare-bundle-compile`. The
 * output is raw modern JS — classes, optional chaining, async
 * iteration, the works.
 *
 * Hermes' parser + AST transformer reject several of those
 * features. Specifically, the bare-events error class shape
 *   class e extends Error { constructor(t,n,r=e,...){...}
 *                           static OPERATION_ABORTED(){...} }
 * triggers a segfault in Hermes'
 * `ES6ClassesTransformations::makeHermesES6InternalCall`
 * (reproducible via libhermes/test/run-zapp-worker.c). The same
 * worker-side gap exists for user bundles, which the Zapp Vite
 * plugin already handles via `hermesCompatLower`.
 *
 * Bare's own bundle gets generated by bare's build, not by Vite,
 * so we need our own intercept. Strategy:
 *
 *   1. After cmake builds bare's bundle target (which writes
 *      `bare.js.h`), read the .h and decode the C byte array
 *      back to the original UTF-8 JS source.
 *   2. Run the same two-pass lower (esbuild es2017 → Babel
 *      transform-classes) used by the Vite plugin.
 *   3. Re-encode as the same C array layout and rewrite the .h
 *      file in place. Mark with `/* zapp-hermes-downleveled *_/`
 *      so a second invocation is a no-op.
 *   4. The on-disk mtime is later than bare.c.o's, so the next
 *      cmake build invocation will rebuild bare.c (and through
 *      it libbare.a, bare_static, bare_bin) — picking up our
 *      lowered bundle.
 *
 * This only runs when bare is being built for the `hermes` engine.
 * Other engine builds skip it and ship native bare.js as before.
 */
import { existsSync } from "node:fs";
import { readFile, writeFile, utimes } from "node:fs/promises";
import path from "node:path";

const MARKER = "/* zapp-hermes-downleveled */";

/**
 * Lower a JS string through the same Hermes-compat pipeline as the
 * Vite plugin: esbuild es2017 (lowers for-await-of, optional
 * chaining, ??, ??=, class fields, private methods) followed by
 * Babel's transform-classes plugin (lowers `class` to ES5
 * prototype chains).
 */
async function lowerForHermes(jsSource: string): Promise<string> {
  // ESM-only import for both packages; we top-level-await them.
  const esbuild = await import("esbuild");
  const esbuildResult = await esbuild.transform(jsSource, {
    target: "es2017",
    minify: false,
    format: "esm",
    sourcemap: false,
  });

  const babel = await import("@babel/core" as string);
  // Babel's plugin export is CJS-shaped — pick `.default` after
  // dynamic import.
  const transformClasses = (await import("@babel/plugin-transform-classes" as string))
    .default;

  const babelResult = await babel.transformAsync(esbuildResult.code, {
    configFile: false,
    babelrc: false,
    plugins: [[transformClasses, { loose: true }]],
    compact: true,
    sourceMaps: false,
  });

  return babelResult?.code ?? esbuildResult.code;
}

/**
 * Extract the JS bytes from a `unsigned char NAME[] = { 0x..., ... };`
 * header. Returns the decoded UTF-8 string.
 */
function extractJsBytes(headerContent: string): string {
  const matches = [...headerContent.matchAll(/0x([0-9a-f]{2})/gi)];
  if (matches.length === 0) {
    throw new Error("[downlevel-bare-js] no byte literals found in header");
  }
  const bytes = Uint8Array.from(matches, (m) => parseInt(m[1], 16));
  return new TextDecoder("utf-8").decode(bytes);
}

/**
 * Re-emit a JS source string as a C header matching the format
 * `cmake-bare-bundle`'s `include-static` produces:
 *
 *   unsigned char NAME[] = {
 *     0x_, 0x_, 0x_, 0x_, ...  // 16 per line
 *   };
 *   size_t NAME_len = N;
 *
 * The variable name is preserved from the original (typically
 * `bare_js`).
 */
function emitCHeader(name: string, source: string): string {
  const bytes = new TextEncoder().encode(source);
  const lines: string[] = [];
  lines.push(`unsigned char ${name}[] = {`);

  const perLine = 16;
  for (let i = 0; i < bytes.length; i += perLine) {
    const chunk = Array.from(bytes.slice(i, i + perLine))
      .map((b) => `0x${b.toString(16).padStart(2, "0")}`)
      .join(", ");
    // Trailing comma on every line except the last (matches the
    // original include-static format — we omit trailing comma on
    // last element but keep `,` between lines).
    const suffix = i + perLine < bytes.length ? "," : "";
    lines.push(`  ${chunk}${suffix}`);
  }

  lines.push("};");
  lines.push("");
  lines.push(`size_t ${name}_len = ${bytes.length};`);
  lines.push(MARKER);
  lines.push("");
  return lines.join("\n");
}

/**
 * If `<bareDir>/src/bare.js.h` exists and hasn't already been
 * downleveled, rewrite it with a Hermes-compatible variant. Idempotent:
 * subsequent calls are no-ops thanks to the embedded marker.
 *
 * Returns `true` if a rewrite happened (caller should rebuild
 * downstream targets), `false` otherwise.
 */
export async function downlevelBareJsForHermes(bareDir: string): Promise<boolean> {
  const hPath = path.join(bareDir, "src", "bare.js.h");
  if (!existsSync(hPath)) {
    // bundle.js hasn't run yet — caller is responsible for ordering.
    return false;
  }

  const content = await readFile(hPath, "utf8");
  if (content.includes(MARKER)) {
    return false; // already downleveled
  }

  // Extract the array name from the first line (`unsigned char NAME[]`).
  const nameMatch = content.match(/unsigned\s+char\s+(\w+)\s*\[\s*\]/);
  const arrayName = nameMatch ? nameMatch[1] : "bare_js";

  process.stdout.write(`[zapp] downleveling bare.js bundle for Hermes...\n`);
  const jsSource = extractJsBytes(content);
  const lowered = await lowerForHermes(jsSource);
  const newHeader = emitCHeader(arrayName, lowered);
  await writeFile(hPath, newHeader);

  // Bump mtime so cmake sees the .h as fresh on the next build.
  const now = new Date();
  await utimes(hPath, now, now);

  const inSize = jsSource.length;
  const outSize = lowered.length;
  process.stdout.write(
    `[zapp] bare.js downleveled: ${inSize} → ${outSize} bytes ` +
    `(+${((outSize - inSize) / 1024).toFixed(1)} KB)\n`,
  );
  return true;
}
