import path from "node:path";
import { existsSync } from "node:fs";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import type { BuildTarget } from "./build-target";
import type { ResolvedConfig } from "./config";
import type { ResolvedCapabilityProfile } from "./capabilities";
import { isPermissionAllowed, resolvePermissions } from "./permissions";
import {
  buildWebviewInjections,
  type BuiltWebviewInjection,
} from "./webview-injections";

export interface ZCompilerIdentity {
  languageVersion: string;
  compilerRevision: string;
  compilerApi: number;
}

export type ZNativeHost = "desktop" | "bridge";

export interface ZNativeStageFile {
  source: string;
  destination: string;
}

export const zNativeDesktopHostEntry = "native-bridge.m";

export const zNativeDesktopHostSources = [
  zNativeDesktopHostEntry,
  "application-host.m",
  "asset-bridge.m",
  "webview-bridge.m",
  "window-bridge.m",
] as const;

export interface ZNativeLinkRequirements {
  includeDirectories?: string[];
  directories?: string[];
  libraries?: string[];
  frameworks?: string[];
}

interface ZCompilerContract extends ZCompilerIdentity {}

interface BuildNativeZOptions {
  root: string;
  nativeDir: string;
  output: string;
  optimize: boolean;
  target: BuildTarget;
  config: ResolvedConfig;
  /** Development frontend origin. Absent means packaged embedded assets. */
  devUrl?: string;
}

function renderZCapabilityProfiles(
  profiles: ResolvedCapabilityProfile[],
): string {
  const statements: string[] = ["  let profiles = Map<String, CapabilityProfile>();"];
  profiles.forEach((profile, index) => {
    statements.push(`  let permissions${index} = Array<String>();`);
    for (const permission of profile.permissions) {
      statements.push(`  permissions${index}.push(${JSON.stringify(permission)});`);
    }
    statements.push(`  let serviceMethods${index} = Array<String>();`);
    for (const method of profile.serviceMethods) {
      statements.push(`  serviceMethods${index}.push(${JSON.stringify(method)});`);
    }
    statements.push(
      `  profiles.set(${JSON.stringify(profile.name)}, CapabilityProfile({`,
      `    permissions: permissions${index}.freeze(),`,
      `    serviceMethods: serviceMethods${index}.freeze(),`,
      "  }));",
    );
  });
  statements.push(
    "  return new ApplicationCapabilities({ profiles: profiles.freeze() });",
  );
  return statements.join("\n");
}

export function renderZApplicationMetadata(
  config: ResolvedConfig,
  capabilityProfiles: ResolvedCapabilityProfile[] = [{
    name: "default",
    permissions: [],
    serviceMethods: [],
  }],
): string {
  return `// AUTO-GENERATED by zapp CLI. Do not edit.
import { Map } from "std/collections";
import {
  ApplicationCapabilities,
  CapabilityProfile,
} from "./application-capabilities.zs";
import { ApplicationMetadata } from "./application-metadata.zs";
import { ApplicationPermissions } from "./application-permissions.zs";

export function configuredApplicationMetadata(): ApplicationMetadata {
  return ApplicationMetadata({
    name: ${JSON.stringify(config.name)},
    identifier: ${JSON.stringify(config.identifier)},
    version: ${JSON.stringify(config.version)},
  });
}

export function configuredApplicationPermissions(): ApplicationPermissions {
  return ApplicationPermissions({
    windowCreate: ${isPermissionAllowed(
      "window:create",
      resolvePermissions(config.permissions),
    )},
  });
}

export function configuredApplicationCapabilities(): ApplicationCapabilities {
${renderZCapabilityProfiles(capabilityProfiles)}
}
`;
}

export function renderZWebviewBootstrapConfig(
  config: ResolvedConfig,
  target: BuildTarget,
): string {
  const resolved = resolvePermissions(config.permissions);
  const platform = target === "macos"
    ? "macos"
    : target === "windows"
      ? "windows"
      : "ios";
  return `globalThis[Symbol.for("zapp.bootstrapConfig")]=${JSON.stringify({
    permissions: {
      platform,
      active: resolved.active,
      allow: resolved.allow,
    },
  })};\n`;
}

export function parseZCompilerIdentity(output: string): ZCompilerIdentity {
  const match = output.trim().match(
    /^z\s+(\S+)\s+revision\s+(\S+)\s+compiler-api\s+(\d+)$/,
  );
  if (!match) {
    throw new Error(
      `[zapp] could not parse Z compiler identity ${JSON.stringify(output.trim())}. ` +
      "Zapp requires a compiler that supports `z version`.",
    );
  }
  return {
    languageVersion: match[1],
    compilerRevision: match[2],
    compilerApi: Number(match[3]),
  };
}

export function validateZCompilerIdentity(
  expected: ZCompilerIdentity,
  actual: ZCompilerIdentity,
  contractPath: string,
): void {
  const differences: string[] = [];
  if (actual.languageVersion !== expected.languageVersion) {
    differences.push(`language ${actual.languageVersion} (expected ${expected.languageVersion})`);
  }
  if (actual.compilerRevision !== expected.compilerRevision) {
    differences.push(`revision ${actual.compilerRevision} (expected ${expected.compilerRevision})`);
  }
  if (actual.compilerApi !== expected.compilerApi) {
    differences.push(`compiler API ${actual.compilerApi} (expected ${expected.compilerApi})`);
  }
  if (differences.length > 0) {
    throw new Error(
      `[zapp] incompatible Z compiler: ${differences.join(", ")}. ` +
      `Use the compiler pinned by ${contractPath} or update the contract after validating Zapp.`,
    );
  }
}

export function resolveZCompiler(repositoryRoot: string): string {
  if (process.env.ZAPP_Z_COMPILER) return process.env.ZAPP_Z_COMPILER;
  const sibling = path.resolve(repositoryRoot, "../z-lang/.z-cache/bootstrap/z");
  return existsSync(sibling) ? sibling : "z";
}

export function resolveZCompilerCommand(repositoryRoot: string): string[] {
  const driver = process.env.ZAPP_Z_COMPILER_DRIVER ?? "native";
  if (driver === "native") return [resolveZCompiler(repositoryRoot)];
  if (driver !== "stage0") {
    throw new Error(
      `[zapp] ZAPP_Z_COMPILER_DRIVER must be "native" or "stage0", not ${JSON.stringify(driver)}.`,
    );
  }
  const entry = path.resolve(repositoryRoot, "../z-lang/compiler/src/cli.ts");
  if (!existsSync(entry)) {
    throw new Error(
      `[zapp] the Stage 0 Z driver was requested, but ${entry} does not exist. ` +
      "Use the sibling z-lang development workspace or select the native driver.",
    );
  }
  return [process.execPath, entry];
}

export function resolveZNativeHost(value: string | undefined): ZNativeHost {
  const host = value ?? "desktop";
  if (host !== "desktop" && host !== "bridge") {
    throw new Error(
      `[zapp] ZAPP_Z_HOST must be "desktop" or "bridge", not ${JSON.stringify(host)}.`,
    );
  }
  return host;
}

export function zNativeStageFiles(host: ZNativeHost): ZNativeStageFile[] {
  return [
    {
      source: "framework/bridge/zapp_router.h",
      destination: "zapp_router.h",
    },
    {
      source: "framework/bridge/zapp_router.h.zd",
      destination: "zapp_router.h.zd",
    },
    ...(host === "desktop" ? [
      ...zNativeDesktopHostSources.map((destination) => ({
        source: `framework/platform/macos/${destination}`,
        destination,
      })),
      {
        source: "framework/platform/macos/desktop-smoke.h",
        destination: "desktop-smoke.h",
      },
      {
        source: "framework/platform/macos/desktop-smoke.m",
        destination: "desktop-smoke.m",
      },
      {
        source: "framework/platform/macos/zapp_desktop.h",
        destination: "zapp_desktop.h",
      },
    ] : [{
      source: "testing/bridge-host.c",
      destination: "host.c",
    }]),
  ];
}

export function zNativeEntry(host: ZNativeHost): string {
  return host === "desktop" ? "main.zs" : "embedded.zs";
}

export function renderZNativeManifest(
  host: ZNativeHost,
  entry: string,
  nativeDirectory = ".",
  packageDirectory?: string,
  application: ZNativeLinkRequirements = {},
): string {
  const unique = (values: string[]): string[] => [...new Set(values)];
  const target = host === "desktop"
    ? {
      name: "zapp_core",
      entry,
      platform: "macos",
      minimumVersion: "14.0",
      includeDirectories: unique([
        nativeDirectory,
        ...(application.includeDirectories ?? []),
      ]),
      link: {
        directories: unique([
          nativeDirectory,
          ...(application.directories ?? []),
        ]),
        libraries: unique([
          "zapp_desktop_host",
          "compression",
          ...(application.libraries ?? []),
        ]),
        frameworks: unique(application.frameworks ?? []),
      },
    }
    : {
      kind: "static-library",
      name: "zapp_core",
      entry,
      platform: "macos",
      minimumVersion: "14.0",
      includeDirectories: [nativeDirectory],
      runtime: { initialize: "initializeApplication" },
    };
  const dependencies = packageDirectory
    ? { zapp: { path: packageDirectory } }
    : undefined;
  return `${JSON.stringify({
    ...(dependencies ? { dependencies } : {}),
    target,
  }, null, 2)}\n`;
}

function manifestStringList(value: unknown, label: string): string[] {
  if (value === undefined) return [];
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw new Error(`[zapp] ${label} in zapp/z.json must be an array of strings`);
  }
  return value;
}

async function readZApplicationLinkRequirements(
  appSource: string,
): Promise<ZNativeLinkRequirements> {
  const manifestPath = path.join(appSource, "z.json");
  if (!existsSync(manifestPath)) return {};
  const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as {
    target?: {
      includeDirectories?: unknown;
      link?: {
        directories?: unknown;
        libraries?: unknown;
        frameworks?: unknown;
      };
    };
  };
  const absolute = (values: string[]): string[] => values.map((directory) => (
    path.isAbsolute(directory) ? directory : path.resolve(appSource, directory)
  ));
  return {
    includeDirectories: absolute(manifestStringList(
      manifest.target?.includeDirectories,
      "target.includeDirectories",
    )),
    directories: absolute(manifestStringList(
      manifest.target?.link?.directories,
      "target.link.directories",
    )),
    libraries: manifestStringList(
      manifest.target?.link?.libraries,
      "target.link.libraries",
    ),
    frameworks: manifestStringList(
      manifest.target?.link?.frameworks,
      "target.link.frameworks",
    ),
  };
}

export function resolveZFrontendOrigin(devUrl?: string): string {
  if (!devUrl) return "zapp://app/";
  const parsed = new URL(devUrl);
  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw new Error(
      `[zapp] the frontend development URL must use http or https, not ${JSON.stringify(parsed.protocol)}.`,
    );
  }
  parsed.hash = "";
  parsed.search = "";
  if (!parsed.pathname.endsWith("/")) parsed.pathname += "/";
  return parsed.toString();
}

export function renderZConfiguredWebView(
  bootstrap: string,
  frontendOrigin: string,
  injections: BuiltWebviewInjection[],
): string {
  const development = frontendOrigin.startsWith("http://")
    || frontendOrigin.startsWith("https://");
  let source = `// AUTO-GENERATED by zapp CLI. Do not edit.\n\n`;
  source += `internal struct ConfiguredWebViewInjection {\n`;
  source += `  profile: String;\n`;
  source += `  source: String;\n`;
  source += `  phase: i32;\n`;
  source += `}\n\n`;
  source += `internal function configuredFrontendOrigin(): String {\n`;
  source += `  return ${JSON.stringify(frontendOrigin)};\n`;
  source += `}\n\n`;
  source += `internal function configuredFrontendIsDevelopment(): boolean {\n`;
  source += `  return ${development};\n`;
  source += `}\n\n`;
  source += `internal function configuredWebViewBootstrap(): String {\n`;
  source += `  return ${JSON.stringify(bootstrap)};\n`;
  source += `}\n\n`;
  source += `internal function configuredWebViewInjectionCount(): usize {\n`;
  source += `  return ${injections.length};\n`;
  source += `}\n\n`;
  source += `internal function configuredWebViewInjectionAtIndex(\n`;
  source += `  index: usize\n`;
  source += `): Option<ConfiguredWebViewInjection> {\n`;
  injections.forEach((entry, index) => {
    source += `  if (index == ${index}) {\n`;
    source += `    return Option.some(ConfiguredWebViewInjection({\n`;
    source += `      profile: ${JSON.stringify(entry.profile)},\n`;
    source += `      source: ${JSON.stringify(entry.source)},\n`;
    source += `      phase: ${entry.phase},\n`;
    source += `    }));\n`;
    source += `  }\n`;
  });
  source += `  return Option.none;\n`;
  source += `}\n`;
  return source;
}

async function run(command: string[], cwd: string, capture = false): Promise<string> {
  const process = Bun.spawn(command, {
    cwd,
    stdout: capture ? "pipe" : "inherit",
    stderr: capture ? "pipe" : "inherit",
  });
  const stdout = capture ? await new Response(process.stdout).text() : "";
  const stderr = capture ? await new Response(process.stderr).text() : "";
  const status = await process.exited;
  if (status !== 0) {
    throw new Error(
      `[zapp] command failed (${status}): ${command.join(" ")}` +
      (stderr.trim() ? `\n${stderr.trim()}` : ""),
    );
  }
  return stdout;
}

export async function assertZCompilerContract(
  compiler: string[],
  contractPath: string,
  cwd: string,
): Promise<ZCompilerIdentity> {
  const expected = JSON.parse(await readFile(contractPath, "utf8")) as ZCompilerContract;
  const actual = parseZCompilerIdentity(await run([...compiler, "version"], cwd, true));
  validateZCompilerIdentity(expected, actual, contractPath);
  return actual;
}

export async function buildNativeZ(options: BuildNativeZOptions): Promise<void> {
  if (options.target !== "macos") {
    throw new Error(
      `[zapp] the Phase 0 Z native core currently supports target "macos", not ${JSON.stringify(options.target)}.`,
    );
  }

  const source = path.join(options.nativeDir, "z");
  const appSource = path.join(options.root, "zapp");
  const repositoryRoot = path.resolve(options.nativeDir, "..");
  const stage = path.join(options.root, ".zapp", "z-native-core");
  const workspace = path.join(stage, "workspace");
  const host = resolveZNativeHost(process.env.ZAPP_Z_HOST);
  const desktop = host === "desktop";
  const desktopSmokeSupport = desktop
    && process.env.ZAPP_Z_DESKTOP_SMOKE_SUPPORT === "1";
  const sourceEntry = path.join(appSource, zNativeEntry(host));
  if (!existsSync(sourceEntry)) {
    throw new Error(
      `[zapp] could not find the Z application entry ${sourceEntry}. ` +
      `Expected ${zNativeEntry(host)} under the project's zapp/ directory.`,
    );
  }
  const applicationLinkRequirements = await readZApplicationLinkRequirements(
    appSource,
  );
  const appRelative = path.relative(repositoryRoot, appSource);
  if (appRelative.startsWith("..") || path.isAbsolute(appRelative)) {
    throw new Error(
      `[zapp] the current Z application spike must live inside ${repositoryRoot}; ` +
      `package-resolved framework imports are the next productization layer.`,
    );
  }
  await mkdir(stage, { recursive: true });
  for (const obsolete of [
    "desktop.m",
    "zapp_frontend_assets.c",
    "zapp_frontend_assets.o",
    "zapp_application_host.o",
    "zapp_asset_bridge.o",
    "zapp_frontend_config.c",
    "zapp_frontend_config.o",
    "zapp_webview_bootstrap.c",
    "zapp_webview_bootstrap.o",
    "zapp_webview_bridge.o",
    "zapp_webview_injections.c",
    "zapp_webview_injections.o",
    "zapp_window_bridge.o",
  ]) {
    await rm(path.join(stage, obsolete), { force: true });
  }
  await rm(workspace, { recursive: true, force: true });
  const stagedFramework = path.join(workspace, "native", "z", "framework");
  await cp(
    path.join(source, "framework"),
    stagedFramework,
    { recursive: true },
  );
  await cp(
    path.join(source, "api"),
    path.join(workspace, "native", "z", "api"),
    { recursive: true },
  );
  await cp(
    path.join(source, "z.json"),
    path.join(workspace, "native", "z", "z.json"),
  );
  await writeFile(
    path.join(stagedFramework, "configured-application.zs"),
    renderZApplicationMetadata(options.config),
    "utf8",
  );
  if (desktop) {
    const { generateAssetManifestZ } = await import("./assets");
    await generateAssetManifestZ(
      options.root,
      options.config.assetDir,
      {
        embed: !options.devUrl,
        compress: options.config.compressAssets !== false,
        outputPath: path.join(
          stagedFramework,
          "platform",
          "macos",
          "configured-assets.zs",
        ),
      },
    );
  }
  const stagedAppSource = path.join(workspace, appRelative);
  await cp(appSource, stagedAppSource, { recursive: true });
  // The source-local manifest exists for direct editor/check context. The
  // isolated workspace has a generated root manifest that additionally owns
  // its generated host archive, so it must remain the single build authority.
  await rm(path.join(stagedAppSource, "z.json"), { force: true });
  const appEntry = path.join(stagedAppSource, zNativeEntry(host));
  for (const file of zNativeStageFiles(host)) {
    const destination = path.join(stage, file.destination);
    await mkdir(path.dirname(destination), { recursive: true });
    await cp(path.join(source, file.source), destination);
  }
  await writeFile(
    path.join(stage, "z.json"),
    renderZNativeManifest(
      host,
      appEntry,
      stage,
      path.join(workspace, "native", "z"),
      applicationLinkRequirements,
    ),
    "utf8",
  );

  const compiler = resolveZCompilerCommand(
    path.resolve(options.nativeDir, ".."),
  );
  const identity = await assertZCompilerContract(
    compiler,
    path.join(source, "compiler-contract.json"),
    options.root,
  );
  console.log(
    `[zapp] Z core compiler ${identity.languageVersion} ` +
    `(revision ${identity.compilerRevision}, API ${identity.compilerApi}, ` +
    `${process.env.ZAPP_Z_COMPILER_DRIVER === "stage0" ? "Stage 0" : "native"} driver)`,
  );

  const { resolveBootstrapDir } = await import("./paths");
  const {
    generateZServiceBindings,
    renderZServiceWebviewRuntime,
  } = await import("./z-service-bindings");
  const { generateZServiceDispatchers } = await import(
    "./z-service-dispatcher"
  );
  const { generateZServiceRegistrationOverlay } = await import(
    "./z-service-registration"
  );
  const {
    deriveZServiceManifest,
    parseZProgramMetadata,
  } = await import("./z-program-metadata");
  const { resolveCapabilityProfiles } = await import("./capabilities");
  const { bundleWebviewBootstrapRaw } = await import(
    path.join(resolveBootstrapDir(), "codegen.ts")
  );
  const programMetadataSource = await run(
    [...compiler, "metadata", stage],
    options.root,
    true,
  );
  await writeFile(
    path.join(stage, "program.zmeta.json"),
    programMetadataSource,
    "utf8",
  );
  const serviceManifest = deriveZServiceManifest(
    parseZProgramMetadata(programMetadataSource),
  );
  const capabilityProfiles = resolveCapabilityProfiles(
    options.config,
    serviceManifest,
  );
  await writeFile(
    path.join(stagedFramework, "configured-application.zs"),
    renderZApplicationMetadata(options.config, capabilityProfiles),
    "utf8",
  );
  await writeFile(
    path.join(stage, "capabilities.zmeta.json"),
    `${JSON.stringify({ schemaVersion: 1, profiles: capabilityProfiles }, null, 2)}\n`,
    "utf8",
  );
  await writeFile(
    path.join(stage, "services.zmeta.json"),
    `${JSON.stringify(serviceManifest, null, 2)}\n`,
    "utf8",
  );
  const dispatcher = await generateZServiceDispatchers(
    serviceManifest,
    {
      outputPath: path.join(stage, "generated", "service-dispatchers.zs"),
      serviceContractModule: path.join(
        workspace,
        "native",
        "z",
        "framework",
        "service-contract.zs",
      ),
      servicesModule: path.join(
        workspace,
        "native",
        "z",
        "framework",
        "services.zs",
      ),
      asyncServiceContractModule: path.join(
        workspace,
        "native",
        "z",
        "framework",
        "async-service-contract.zs",
      ),
      serviceLifecycleContractModule: path.join(
        workspace,
        "native",
        "z",
        "api",
        "zapp",
        "service.zs",
      ),
    },
  );
  await run([...compiler, "check", dispatcher], options.root, true);
  console.log(`[zapp] checked generated Z service dispatch ${dispatcher}`);
  const registrationOverlay = await generateZServiceRegistrationOverlay(
    serviceManifest,
    dispatcher,
    path.join(stage, "generated", "service-registration.zbuild.json"),
  );
  console.log(`[zapp] generated checked Z service registration ${registrationOverlay}`);
  const generatedBinding = await generateZServiceBindings(
    serviceManifest,
    path.join(options.root, ".zapp", "generated"),
  );
  console.log(`[zapp] generated typed Z service bindings ${generatedBinding}`);
  const bootstrapSource = renderZWebviewBootstrapConfig(options.config, options.target)
    + await bundleWebviewBootstrapRaw()
    + renderZServiceWebviewRuntime(serviceManifest);
  if (desktop) {
    const injectionEntries = await buildWebviewInjections(
      options.root,
      options.config.webviewInject,
      options.optimize,
    );
    await writeFile(
      path.join(
        stagedFramework,
        "platform",
        "macos",
        "configured-webview.zs",
      ),
      renderZConfiguredWebView(
        bootstrapSource,
        resolveZFrontendOrigin(options.devUrl),
        injectionEntries,
      ),
      "utf8",
    );
  }

  const clang = process.env.CC || "clang";
  if (desktop) {
    const desktopObject = path.join(stage, "zapp_desktop_host.o");
    const desktopSmokeObject = path.join(stage, "zapp_desktop_smoke.o");
    const desktopArchive = path.join(stage, "libzapp_desktop_host.a");
    await run([
      clang,
      "-fobjc-arc",
      "-fblocks",
      "-mmacosx-version-min=14.0",
      options.optimize ? "-Oz" : "-O0",
      "-Wall",
      "-Wextra",
      "-Werror",
      ...(desktopSmokeSupport ? ["-DZAPP_DESKTOP_SMOKE_SUPPORT=1"] : []),
      "-I",
      stage,
      "-c",
      path.join(stage, zNativeDesktopHostEntry),
      "-o",
      desktopObject,
    ], options.root);
    if (desktopSmokeSupport) {
      await run([
        clang,
        "-fobjc-arc",
        "-fblocks",
        "-mmacosx-version-min=14.0",
        options.optimize ? "-Oz" : "-O0",
        "-Wall",
        "-Wextra",
        "-Werror",
        "-I",
        stage,
        "-c",
        path.join(stage, "desktop-smoke.m"),
        "-o",
        desktopSmokeObject,
      ], options.root);
    } else {
      await rm(desktopSmokeObject, { force: true });
    }
    await rm(desktopArchive, { force: true });
    await run([
      "ar",
      "rcs",
      desktopArchive,
      desktopObject,
      ...(desktopSmokeSupport ? [desktopSmokeObject] : []),
    ], options.root);
  }

  await run(
    [
      ...compiler,
      "build",
      stage,
      "--generated",
      registrationOverlay,
      ...(options.optimize ? ["--release"] : []),
    ],
    options.root,
  );

  await mkdir(path.dirname(options.output), { recursive: true });
  if (desktop) {
    await cp(path.join(stage, "build", "zapp_core"), options.output);
    return;
  }
  const archive = path.join(stage, "build", "libzapp_core.a");
  const headerDir = path.join(stage, "build");
  await run([
    clang,
    "-std=c11",
    "-mmacosx-version-min=14.0",
    options.optimize ? "-Oz" : "-O0",
    "-Wall",
    "-Wextra",
    "-Werror",
    "-I",
    headerDir,
    path.join(stage, "host.c"),
    archive,
    "-o",
    options.output,
  ], options.root);
}
