import path from "node:path";
import { readFile } from "node:fs/promises";
import type { WebviewInjectProfile } from "./config";

export const WEBVIEW_INJECT_STYLE = 0;
export const WEBVIEW_INJECT_DOCUMENT_START = 1;
export const WEBVIEW_INJECT_DOCUMENT_END = 2;

export interface BuiltWebviewInjection {
  profile: string;
  phase: 0 | 1 | 2;
  sourcePath: string;
  source: string;
}

const scriptExtensions = new Set([
  ".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts",
]);

async function readStyle(root: string, profile: string, sourcePath: string) {
  if (path.extname(sourcePath).toLowerCase() !== ".css") {
    throw new Error(
      `[zapp] webview.inject.${profile}.styles entry ${JSON.stringify(sourcePath)} ` +
      "must be a .css file",
    );
  }
  try {
    return await readFile(path.resolve(root, sourcePath), "utf8");
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(
      `[zapp] could not read webview.inject.${profile} style ` +
      `${JSON.stringify(sourcePath)}: ${detail}`,
    );
  }
}

async function bundleScript(
  root: string,
  profile: string,
  phase: "documentStart" | "documentEnd",
  sourcePath: string,
  optimize: boolean,
): Promise<string> {
  if (!scriptExtensions.has(path.extname(sourcePath).toLowerCase())) {
    throw new Error(
      `[zapp] webview.inject.${profile}.${phase} entry ${JSON.stringify(sourcePath)} ` +
      "must be a JavaScript or TypeScript file",
    );
  }
  const absolute = path.resolve(root, sourcePath);
  const result = await Bun.build({
    entrypoints: [absolute],
    target: "browser",
    format: "iife",
    minify: optimize,
  });
  if (!result.success || result.outputs.length !== 1) {
    const details = result.logs.map((log) => log.message).join("\n");
    throw new Error(
      `[zapp] could not bundle webview.inject.${profile}.${phase} ` +
      `${JSON.stringify(sourcePath)}${details ? `:\n${details}` : ""}`,
    );
  }
  return await result.outputs[0].text();
}

export async function buildWebviewInjections(
  root: string,
  catalog: Record<string, WebviewInjectProfile> | undefined,
  optimize: boolean,
): Promise<BuiltWebviewInjection[]> {
  if (catalog === undefined) return [];
  const entries: BuiltWebviewInjection[] = [];
  for (const [profile, definition] of Object.entries(catalog)) {
    for (const sourcePath of definition.styles ?? []) {
      entries.push({
        profile,
        phase: WEBVIEW_INJECT_STYLE,
        sourcePath,
        source: await readStyle(root, profile, sourcePath),
      });
    }
    for (const sourcePath of definition.documentStart ?? []) {
      entries.push({
        profile,
        phase: WEBVIEW_INJECT_DOCUMENT_START,
        sourcePath,
        source: await bundleScript(
          root, profile, "documentStart", sourcePath, optimize,
        ),
      });
    }
    for (const sourcePath of definition.documentEnd ?? []) {
      entries.push({
        profile,
        phase: WEBVIEW_INJECT_DOCUMENT_END,
        sourcePath,
        source: await bundleScript(
          root, profile, "documentEnd", sourcePath, optimize,
        ),
      });
    }
  }
  return entries;
}

function renderByteArray(bytes: Uint8Array): string {
  const values = [...bytes, 0];
  const rows: string[] = [];
  for (let offset = 0; offset < values.length; offset += 16) {
    rows.push(
      "  " + values.slice(offset, offset + 16)
        .map((byte) => `0x${byte.toString(16).padStart(2, "0")}`)
        .join(", "),
    );
  }
  return rows.join(",\n");
}

export function renderWebviewInjectionsC(
  entries: BuiltWebviewInjection[],
): string {
  const encoder = new TextEncoder();
  const sources = entries.map((entry, index) =>
    `static const unsigned char zapp_webview_injection_${index}[] = {\n` +
    `${renderByteArray(encoder.encode(entry.source))}\n};`);
  const table = entries.length === 0
    ? ""
    : `static const ZAppWebviewInjection zapp_webview_injections[] = {\n` +
      entries.map((entry, index) =>
        `  {${JSON.stringify(entry.profile)}, ${entry.phase}, ` +
        `zapp_webview_injection_${index}, ` +
        `${encoder.encode(entry.source).length}},`).join("\n") +
      `\n};`;
  const getter = (field: string, fallback: string) => entries.length === 0
    ? `  (void)index;\n  return ${fallback};`
    : `  if (index >= ${entries.length}) return ${fallback};\n` +
      `  return zapp_webview_injections[index].${field};`;
  return `// AUTO-GENERATED by zapp CLI. Do not edit.
#include <stddef.h>
#include <stdint.h>

typedef struct {
  const char *profile;
  int32_t phase;
  const unsigned char *source;
  size_t source_length;
} ZAppWebviewInjection;

${sources.join("\n\n")}
${sources.length > 0 ? "\n" : ""}${table}

size_t zapp_webview_injection_count(void) {
  return ${entries.length};
}

const char *zapp_webview_injection_profile(size_t index) {
${getter("profile", "NULL")}
}

int32_t zapp_webview_injection_phase(size_t index) {
${getter("phase", "-1")}
}

const unsigned char *zapp_webview_injection_source(size_t index) {
${getter("source", "NULL")}
}

size_t zapp_webview_injection_source_length(size_t index) {
${getter("source_length", "0")}
}
`;
}
